# Assemble Data

In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
from scipy.ndimage import uniform_filter1d  # simple smoothing
import re

In [2]:
pd.set_option('display.max_columns', None)  # show all columns
# pd.set_option('display.max_rows', None)  # show all columns
# import os
# os.chdir('..')

### Start with plot features

In [3]:
# get elevation features
df = pd.read_pickle('../data/plot_elev_features.pkl')

In [4]:
df

,plot_id,slope_mean,slope_min,slope_max,curve_mean,curve_min,curve_max,pro_curve_mean,pro_curve_min,pro_curve_max,plan_curve_mean,plan_curve_min,plan_curve_max,aspect_mean,aspect_min,aspect_max,elev_min,elev_max,elev_mean,elev_dev_min,elev_dev_max,elev_dev_mean,geometry,total_relief,area_m2,area_ha
0,0,5.020058,3.925700,6.804783,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,175.379315,155.373535,190.393188,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,"POLYGON ((-119.78208 45.87245, -119.78215 45.8...",1.525681,451.141838,0.045114
1,1,5.289605,3.356515,8.816703,-0.000258,-0.014769,0.013737,-0.001123,-0.016449,0.012478,-0.000258,-0.014769,0.013737,169.123825,144.559204,188.072983,206.874710,208.469513,207.776839,21.910873,23.505676,22.812984,"POLYGON ((-119.78179 45.87245, -119.78167 45.8...",1.594803,381.909845,0.038191
2,2,7.150476,4.206255,11.814886,0.000065,-0.030229,0.034444,-0.000754,-0.043223,0.027175,0.000065,-0.030229,0.034444,152.046614,135.318848,175.093628,205.507690,207.790955,206.759655,20.543854,22.827118,21.795817,"POLYGON ((-119.78139 45.87246, -119.78129 45.8...",2.283264,304.757142,0.030476
3,3,9.178217,5.255136,12.657069,0.000241,-0.022650,0.018867,0.000610,-0.020701,0.012653,0.000241,-0.022650,0.018867,175.202423,159.699402,189.218704,210.499161,214.308624,212.434447,25.535324,29.344788,27.470613,"POLYGON ((-119.78299 45.87287, -119.78300 45.8...",3.809464,416.261511,0.041626
4,4,6.641992,4.568419,10.110537,0.000753,-0.013419,0.014943,0.000611,-0.011132,0.012551,0.000753,-0.013419,0.014943,173.372281,156.050049,189.273071,209.319901,213.504730,211.261849,24.356064,28.540894,26.298020,"POLYGON ((-119.78263 45.87269, -119.78269 45.8...",4.184830,934.859055,0.093486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3593,3593,6.524146,4.537724,8.501439,-0.001274,-0.024254,0.019990,-0.001476,-0.019637,0.020838,-0.001274,-0.024254,0.019990,163.878749,140.306885,186.459793,228.098480,232.209412,230.327266,43.134644,47.245575,45.363431,"POLYGON ((-119.77610 45.87519, -119.77626 45.8...",4.110931,544.855651,0.054486
3594,3594,3.070807,1.769737,4.388859,0.000577,-0.013051,0.017839,0.000672,-0.015131,0.010445,0.000577,-0.013051,0.017839,176.192068,142.778198,228.122147,234.638351,235.519440,235.030851,49.674515,50.555603,50.067012,"POLYGON ((-119.77718 45.87568, -119.77718 45.8...",0.881088,319.126138,0.031913
3595,3595,3.290681,1.204210,6.403341,-0.001655,-0.029511,0.026497,-0.002227,-0.026850,0.022847,-0.001655,-0.029511,0.026497,210.650471,141.063812,265.084839,235.022568,236.736877,235.759766,50.058731,51.773041,50.795942,"POLYGON ((-119.77685 45.87573, -119.77680 45.8...",1.714310,591.653344,0.059165
3596,3596,6.540738,1.204210,9.352532,-0.000439,-0.029511,0.027310,-0.001295,-0.025244,0.019796,-0.000439,-0.029511,0.027310,140.301358,110.309143,226.955688,232.924850,236.760712,235.060714,47.961014,51.796875,50.096894,"POLYGON ((-119.77652 45.87579, -119.77642 45.8...",3.835861,847.012539,0.084701
3597,3597,4.773266,3.095966,7.210205,-0.000758,-0.019660,0.016977,0.001952,-0.012836,0.017013,-0.000758,-0.019660,0.016977,160.983810,131.892456,196.518311,232.254944,235.135742,233.620047,47.291107,50.171906,48.656196,"POLYGON ((-119.77612 45.87557, -119.77618 45.8...",2.880798,940.121044,0.094012

### Compute vectors for aspect and slope, and some interaction terms

In [5]:
# Aspect: convert to radians and compute sin/cos
df['aspect_min_cos'] = np.cos(np.radians(df['aspect_min']))
df['aspect_min_sin'] = np.sin(np.radians(df['aspect_min']))

df['aspect_max_cos'] = np.cos(np.radians(df['aspect_max']))
df['aspect_max_sin'] = np.sin(np.radians(df['aspect_max']))

df['aspect_mean_cos'] = np.cos(np.radians(df['aspect_mean']))
df['aspect_mean_sin'] = np.sin(np.radians(df['aspect_mean']))

# Drop raw aspect values
df = df.drop(columns=['aspect_min', 'aspect_max', 'aspect_mean'])

df['slope_rad'] = np.radians(df['slope_mean'])
df['slope_grad'] = np.tan(df['slope_rad'])


df['slope_x'] = df['slope_grad'] * df['aspect_mean_cos']
df['slope_y'] = df['slope_grad'] * df['aspect_mean_sin']

df = df.drop(columns = ['slope_mean','slope_min','slope_max'])

In [6]:
df

,plot_id,curve_mean,curve_min,curve_max,pro_curve_mean,pro_curve_min,pro_curve_max,plan_curve_mean,plan_curve_min,plan_curve_max,elev_min,elev_max,elev_mean,elev_dev_min,elev_dev_max,elev_dev_mean,geometry,total_relief,area_m2,area_ha,aspect_min_cos,aspect_min_sin,aspect_max_cos,aspect_max_sin,aspect_mean_cos,aspect_mean_sin,slope_rad,slope_grad,slope_x,slope_y
0,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,"POLYGON ((-119.78208 45.87245, -119.78215 45.8...",1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076
1,1,-0.000258,-0.014769,0.013737,-0.001123,-0.016449,0.012478,-0.000258,-0.014769,0.013737,206.874710,208.469513,207.776839,21.910873,23.505676,22.812984,"POLYGON ((-119.78179 45.87245, -119.78167 45.8...",1.594803,381.909845,0.038191,-0.814715,0.579861,-0.990090,-0.140434,-0.982037,0.188687,0.092321,0.092584,-0.090921,0.017469
2,2,0.000065,-0.030229,0.034444,-0.000754,-0.043223,0.027175,0.000065,-0.030229,0.034444,205.507690,207.790955,206.759655,20.543854,22.827118,21.795817,"POLYGON ((-119.78139 45.87246, -119.78129 45.8...",2.283264,304.757142,0.030476,-0.711031,0.703161,-0.996336,0.085528,-0.883329,0.468753,0.124799,0.125451,-0.110815,0.058806
3,3,0.000241,-0.022650,0.018867,0.000610,-0.020701,0.012653,0.000241,-0.022650,0.018867,210.499161,214.308624,212.434447,25.535324,29.344788,27.470613,"POLYGON ((-119.78299 45.87287, -119.78300 45.8...",3.809464,416.261511,0.041626,-0.937885,0.346945,-0.987084,-0.160203,-0.996496,0.083636,0.160190,0.161575,-0.161008,0.013513
4,4,0.000753,-0.013419,0.014943,0.000611,-0.011132,0.012551,0.000753,-0.013419,0.014943,209.319901,213.504730,211.261849,24.356064,28.540894,26.298020,"POLYGON ((-119.78263 45.87269, -119.78269 45.8...",4.184830,934.859055,0.093486,-0.913900,0.405938,-0.986932,-0.161140,-0.993317,0.115418,0.115925,0.116447,-0.115669,0.013440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3593,3593,-0.001274,-0.024254,0.019990,-0.001476,-0.019637,0.020838,-0.001274,-0.024254,0.019990,228.098480,232.209412,230.327266,43.134644,47.245575,45.363431,"POLYGON ((-119.77610 45.87519, -119.77626 45.8...",4.110931,544.855651,0.054486,-0.769476,0.638675,-0.993651,-0.112506,-0.960676,0.277671,0.113868,0.114363,-0.109865,0.031755
3594,3594,0.000577,-0.013051,0.017839,0.000672,-0.015131,0.010445,0.000577,-0.013051,0.017839,234.638351,235.519440,235.030851,49.674515,50.555603,50.067012,"POLYGON ((-119.77718 45.87568, -119.77718 45.8...",0.881088,319.126138,0.031913,-0.796300,0.604902,-0.667545,-0.744570,-0.997792,0.066412,0.053596,0.053647,-0.053529,0.003563
3595,3595,-0.001655,-0.029511,0.026497,-0.002227,-0.026850,0.022847,-0.001655,-0.029511,0.026497,235.022568,236.736877,235.759766,50.058731,51.773041,50.795942,"POLYGON ((-119.77685 45.87573, -119.77680 45.8...",1.714310,591.653344,0.059165,-0.777846,0.628454,-0.085681,-0.996323,-0.860293,-0.509799,0.057433,0.057496,-0.049464,-0.029312
3596,3596,-0.000439,-0.029511,0.027310,-0.001295,-0.025244,0.019796,-0.000439,-0.029511,0.027310,232.924850,236.760712,235.060714,47.961014,51.796875,50.096894,"POLYGON ((-119.77652 45.87579, -119.77642 45.8...",3.835861,847.012539,0.084701,-0.347085,0.937834,-0.682564,-0.730826,-0.769415,0.638750,0.114157,0.114656,-0.088218,0.073236
3597,3597,-0.000758,-0.019660,0.016977,0.001952,-0.012836,0.017013,-0.000758,-0.019660,0.016977,232.254944,235.135742,233.620047,47.291107,50.171906,48.656196,"POLYGON ((-119.77612 45.87557, -119.77618 45.8...",2.880798,940.121044,0.094012,-0.667735,0.744399,-0.958729,-0.284322,-0.945427,0.325835,0.083309,0.083502,-0.078945,0.027208

## Now add NDVI for each plot to features

### open up the filtered and smoothed ndvi df

In [7]:
veg_agg = pd.read_pickle('../data/ndvi/plots/final_df.pkl')
keep_cols = ['plot_id', 'year']

In [8]:
veg_agg = veg_agg.dropna(axis = 1)
veg_agg

,plot_id,year,ndvi_smooth_mean_13,ndvi_smooth_mean_14,ndvi_smooth_mean_15,ndvi_smooth_mean_16,ndvi_smooth_mean_17,ndvi_smooth_mean_18,ndvi_smooth_mean_19,ndvi_smooth_mean_20,ndvi_smooth_mean_21,ndvi_smooth_mean_22,ndvi_smooth_mean_23,ndvi_smooth_mean_24,ndvi_smooth_mean_25,ndvi_smooth_mean_26,ndvi_smooth_mean_27,ndvi_smooth_mean_28,ndvi_smooth_mean_29,ndvi_smooth_mean_30,ndvi_smooth_mean_31,ndvi_smooth_mean_32,ndvi_smooth_mean_33,ndvi_smooth_mean_34,ndvi_smooth_mean_35,ndvi_smooth_mean_36,ndvi_smooth_mean_37,ndvi_smooth_mean_38,ndvi_smooth_mean_39,ndvi_smooth_mean_40,ndvi_smooth_mean_41,ndvi_smooth_mean_42,ndvi_smooth_mean_43,ndvi_smooth_mean_44,ndvi_smooth_mean_45,ndvi_smooth_slope_1,ndvi_smooth_slope_2,ndvi_smooth_slope_3,ndvi_smooth_slope_4,ndvi_smooth_slope_5,ndvi_smooth_slope_6,ndvi_smooth_slope_7,ndvi_smooth_slope_8,ndvi_smooth_slope_9,ndvi_smooth_slope_10,ndvi_smooth_slope_11,ndvi_smooth_slope_12,ndvi_smooth_slope_13,ndvi_smooth_slope_14,ndvi_smooth_slope_15,ndvi_smooth_slope_16,ndvi_smooth_slope_17,ndvi_smooth_slope_18,ndvi_smooth_slope_19,ndvi_smooth_slope_20,ndvi_smooth_slope_21,ndvi_smooth_slope_22,ndvi_smooth_slope_23,ndvi_smooth_slope_24,ndvi_smooth_slope_25,ndvi_smooth_slope_26,ndvi_smooth_slope_27,ndvi_smooth_slope_28,ndvi_smooth_slope_29,ndvi_smooth_slope_30,ndvi_smooth_slope_31,ndvi_smooth_slope_32,ndvi_smooth_slope_33,ndvi_smooth_slope_34,ndvi_smooth_slope_35,ndvi_smooth_slope_36,ndvi_smooth_slope_37,ndvi_smooth_slope_38,ndvi_smooth_slope_39,ndvi_smooth_slope_40,ndvi_smooth_slope_41,ndvi_smooth_slope_42,ndvi_smooth_slope_43,ndvi_smooth_slope_44,ndvi_smooth_slope_45,ndvi_smooth_slope_46,ndvi_smooth_slope_47,ndvi_smooth_slope_48,ndvi_smooth_slope_49,ndvi_smooth_slope_50,ndvi_smooth_slope_51,ndvi_smooth_slope_52,ndvi_smooth_std_1,ndvi_smooth_std_2,ndvi_smooth_std_3,ndvi_smooth_std_4,ndvi_smooth_std_5,ndvi_smooth_std_6,ndvi_smooth_std_7,ndvi_smooth_std_8,ndvi_smooth_std_9,ndvi_smooth_std_10,ndvi_smooth_std_11,ndvi_smooth_std_12,ndvi_smooth_std_13,ndvi_smooth_std_14,ndvi_smooth_std_15,ndvi_smooth_std_16,ndvi_smooth_std_17,ndvi_smooth_std_18,ndvi_smooth_std_19,ndvi_smooth_std_20,ndvi_smooth_std_21,ndvi_smooth_std_22,ndvi_smooth_std_23,ndvi_smooth_std_24,ndvi_smooth_std_25,ndvi_smooth_std_26,ndvi_smooth_std_27,ndvi_smooth_std_28,ndvi_smooth_std_29,ndvi_smooth_std_30,ndvi_smooth_std_31,ndvi_smooth_std_32,ndvi_smooth_std_33,ndvi_smooth_std_34,ndvi_smooth_std_35,ndvi_smooth_std_36,ndvi_smooth_std_37,ndvi_smooth_std_38,ndvi_smooth_std_39,ndvi_smooth_std_40,ndvi_smooth_std_41,ndvi_smooth_std_42,ndvi_smooth_std_43,ndvi_smooth_std_44,ndvi_smooth_std_45,ndvi_smooth_std_46,ndvi_smooth_std_47,ndvi_smooth_std_48,ndvi_smooth_std_49,ndvi_smooth_std_50,ndvi_smooth_std_51,ndvi_smooth_std_52,ndvi_cov,ndvi_mean,ndvi_std,ndvi_mean_norm,ndvi_std_norm,ndvi_cov_norm,health
0,0.0,2016,0.417441,0.417741,0.415264,0.412015,0.410159,0.410159,0.408649,0.406006,0.403366,0.400812,0.398296,0.395780,0.393264,0.390748,0.388232,0.384497,0.373238,0.356197,0.348879,0.346145,0.345504,0.355702,0.381068,0.413351,0.438675,0.443236,0.440521,0.432348,0.424176,0.416003,0.407830,0.379300,0.366964,0.0,0.000000,0.000000,0.000000,0.000000,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,-0.000078,-0.000464,-0.000464,0.000000,0.000000,-0.000378,-0.000378,-0.000376,-0.000359,-0.000359,-0.000359,-0.000359,-0.000359,-0.000359,-0.001071,-0.001783,-0.001851,-0.000534,-0.000351,0.000406,0.003347,0.003689,0.005842,0.000652,0.000652,-0.001168,-0.001168,-0.001168,-0.001168,-0.001168,-0.008094,0.000948,0.000948,0.000948,0.001134,0.001319,0.001319,-0.005969,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000313,0.001003,0.001003,0.000000,0.000000,0.000816,0.000816,0.000811,0.000776,0.000776,0.000776,0.000776,0.000776,0.000776,0.002445,0.003851,0.004258,0.001196,0.000759,0.000913,0.007293,0.007969,0.012621,0.001408,0.001408,0.002522,0.002522,0.002522,0.002522,0.002522,0.018546,0.002048,0.002048,0.002048,0.002457,0.002850,0.002850,0.019600,0.000000,0.061211,0.399301,0.024442,0.488995,0.928728,0.947038,0.677199
1,0.0,2017,0.329644,0.330595,0.331926,0.333256,0.334587,0.338387,0.351077,0.364508,0.376660,0.385999,0.395252,0.404505,0.399311,0.355272,0.339719,0.331969,0.322669,0.320248,0.318124,0.322323,0.324225,0.321754,0.322187,0.327781,0.330168,0.331366,0.333434,0.339194,0.339164,0.338132,0.337109,0.336203,0.335328,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000014,0.000190,0.000190,0.000190,0.000190,0.001425,0.001919,0.001919,0.001386,0.001322,0.001322,0.001322,-0.003970,-0.004277,-0.000937,-0.001231,-0.000664,-0.000828,0.000356,0.000338,0.000090,-0.000614,0.001560,0.000333,0.000323,0.000109,0.000761,0.000437,-0.000147,-0.000147,-0.000141,-0.000125,-0.000125,-0.000125,-0.000275,-0.000650,-0.000046,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000190,0.000411,0.000411,0.000411,0.000411,0.003191,0.004145,0.004145,0.002999,0.002856,0.002856,0.002856,0.008904,0.009495,0.002024,0.002659,0.002196,0.001798,0.001029,0.000758,0.000448,0.001365,0.003402,0.000719,0.000713,0.000236,0.001703,0.001147,0.000319,0.000319,0.000305,0.000270,0.000270,0.000270,0.000647,0.001404,0.000650,0.000000,0.000000,0.000000,0.066718,0.341236,0.022767,0.381518,0.935975,0.938697,0.598005
2,0.0,2018,0.337342,0.339505,0.341668,0.343619,0.344173,0.345555,0.346938,0.343668,0.341470,0.332540,0.330672,0.330827,0.320533,0.319656,0.314177,0.313716,0.306276,0.305823,0.303524,0.306111,0.314969,0.329831,0.339823,0.344996,0.351547,0.354465,0.366220,0.378805,0.389178,0.428417,0.467546,0.480323,0.492458,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000671,0.001297,0.000309,0.000309,0.000309,0.000309,0.000167,0.000197,0.000197,0.000197,-0.000371,-0.000499,-0.001485,0.000213,-0.000566,-0.000727,-0.000688,-0.000402,-0.000188,-0.001330,-0.000526,0.000361,0.000039,0.002017,0.002040,0.000333,0.001936,0.000417,0.000417,0.003317,0.001256,0.002308,0.008811,0.001145,0.003129,0.001009,0.001136,-0.003627,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001467,0.002802,0.000668,0.000668,0.000668,0.000668,0.000435,0.000427,0.000427,0.000427,0.000943,0.001097,0.003556,0.000460,0.001499,0.002002,0.001735,0.000936,0.000503,0.003396,0.001362,0.001030,0.000733,0.004407,0.004407,0.000907,0.004447,0.000901,0.000901,0.007535,0.002714,0.005300,0.019070,0.002474,0.006792,0.002209,0.002454,0.010856,0.000000,0.000000,0.000000,0.000000,0.000000,0.153744,0.355367,0.054636,0.407674,0.798117,0.806869,0.571971
3,0.0,2019,0.420147,0.417991,0.417286,0.416581,0.415876,0.414144,0.390046,0.377250,0.367943,0.333504,0.307616,0.298621,0.277066,0.268343,0.257594,0.253854,0.250562,0.249726,0.247150,0.253554,0.258864,0.258951,0.259078,0.258787,0.258504,0.259266,0.260198,0.260873,0.258438,0.255991,0.253653,0.256494,0.299480,0.0,-0.000042,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000569,-0.000935,-0.000584,-0.000101,-0.000101,-0.000101,-0.000101,-0.001171,-0.003517,-0.001153,-0.002081,-0.003267,-0.001364,-0.002576,-0.002017,-0.002022,-0.001092,-0.000099,-0.000736,0.000314,0.000672,0.000888,0.000297,0.000071,0.000183,-0.000065,0.000034,0.000133,0.000133,-0.000015,-0.000440,-0.000320,-0.000360,0.004201,0.004435,0.002910,0.002761,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000300,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.003862,0.002245,0.001262,0.000218,0.000218,0.000218,0.000218,0.003792,0.007767,0.002490,0.005189,0.007391,0.003863,0.005726,0.005762,0.004371,0.002362,0.000237,0.001595,0.001161,0.001979,0.001919,0.001101,0.000213,0.000487,0.000139,0.000133,0.000287,0.000287,0.000209,0.000959,0.000692,0.000778,0.010231,0.009920,0.006288,0.005965,0.000000,0.000000,0.000000,0.000000,0.000000,0.239423,0.338190,0.080971,0.375880,0.684197,0.677082,0.505802
4,0.0,2020,0.426042,0.420337,0.406763,0.355260,0.309138,0.300667,0.286758,0.282486,0.283371,0.281487,0.275424,0.276846,0.277771,0.275635,0.272246,0.251884,0.244928,0.250605,0.256064,0.264572,0.270360,0.275373,0.277629,0.290302,0.300525,0.303298,0.305589,0.309173,0.300149,0.297698,0.296588,0.295123,0.298194,0.0,0.000000,0.000000,0.000000,0.000000,0.003504,0.006519,-0.000644,-0.002138,-0.000858,-0.000820,-0.000815,-0.000815,-0.000815,-0.005405,-0.010096,-0.001210,-0.001210,-0.002390,0.000126,0.000126,-0.001271,0.000203,0.000203,-0.000086,-0.000376,-0.000880,-0.004101,-0.000571,0.001412,0.000533,0.000191,0.000983,-0.000812,0.001257,0.003374,0.000320,0.000406,0.000286,0.000719,-0.000983,-0.000159,-0.000159,-0.000324,0.000889,0.000889,0.000919,0.001281,0.002587,0.001490,0.001490,0.000106,0.0,0.000000,0.000000,0.000000,0.000000,0.007570,0.014232,0.010650,0.004834,0.001853,0.001771,0.001761,0.001761,0.001761,0.012744,0.023066,0.002614,0.002614,0.005443,0.000273,0.000273,0.002915,0.000439,0.000439,0.000372,0.000812,0.002088,0.009112,0.002349,0.003092,0.002348,0.001516,0.002154,0.002428,0.002928,0.007347,0.000713,0.000878,0.000618,0.001700,0.002553,0.000342,0.000342,0.000808,0.001921,0.001921,0.001986,0.002883,0.005721,0.003218,0.003218,0.001490,0.193982,0.325241,0.063091,0.351912,0.761540,0.745916,0.515006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35975,3597.0,2021,0.260427,0.254365,0.238068,0.243177,0.258024,0.269298,0.281962,0.303152,0.312652,0.337048,0.349271,0.367689,0.385405,0.395900,0.393201,0.389211,0.383006,0.382267,0.381121,0.384151,0.393474,0.398543,0.404984,0.412823,0.412136,0.406469,0.396026,0.382007,0.375481,0.346197,0.340742,0.336458,0.332479,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000295,-0.001003,-0.001538,-0.001078,-0.000786,-0.001236,-0.003111,0.003419,0.001700,0.001543,0.002783,0.001287,0.001658,0.003462,0.001180,0.003152,0.001914,0.000365,-0.000454,-0.000880,-0.000297,-0.000089,-0.000226,0.001517,0.001354,-0.000290,0.001476,0.000050,-0.000759,-0.000988,-0.001916,-0.001027,-0.002268,-0.001490,-0.000612,-0.000612,-0.000383,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002200,0.002173,0.003322,0.002334,0.001701,0.002792,0.006817,0.007630,0.003672,0.003334,0.006374,0.002779,0.003727,0.007875,0.002549,0.006851,0.004136,0.001316,0.001253,0.001907,0.001071,0.000191,0.000524,0.003531,0.002960,0.001357,0.003245,0.000191,0.001687,0.002175,0.004174,0.002499,0.005691,0.004046,0.001322,0.001322,0.001145,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.166675,0.339790,0.056634,0.378842,0.789470,0.787282,0.546506
35976,3597.0,2022,0.273234,0.282769,0.299788,0.317859,0.340028,0.362378,0.381280,0.396742,0.405271,0.413589,0.421907,0.436211,0.482206,0.556552,0.575809,0.595833,0.596200,0.578534,0.573135,0.565441,0.565494,0.559885,0.558400,0.553192,0.558149,0.560238,0.555497,0.526853,0.504118,0.482449,0.461605,0.443183,0.433803,0.0,-0.000617,-0.000617,-0.000617,-0.000617,-0.001793,-0.002065,0.000137,0.000150,0.000254,0.000254,0.000254,0.000410,0.002119,0.002533,0.002760,0.003330,0.002851,0.002659,0.001346,0.001188,0.001188,0.001188,0.004680,0.005997,0.006510,0.002069,0.002524,-0.003017,-0.000683,-0.001046,-0.000590,-0.000223,-0.000601,-0.000334,-0.000414,0.001284,-0.000359,-0.002051,-0.005354,-0.002417,-0.002735,-0.004635,-0.001340,-0.001340,-0.002604,-0.004022,-0.002078,0.000000,0.000000,0.000000,0.000000,0.0,0.001333,0.001333,0.001333,0.001333,0.003892,0.005833,0.000296,0.000325,0.000550,0.000550,0.000550,0.000986,0.004600,0.005471,0.005976,0.007193,0.006167,0.005744,0.002941,0.002567,0.002567,0.002567,0.010830,0.012976,0.015745,0.004665,0.005471,0.006645,0.001748,0.002318,0.001439,0.001081,0.001445,0.000960,0.001327,0.002839,0.000932,0.004474,0.011930,0.005222,0.006028,0.010198,0.002895,0.002895,0.006027,0.008769,0.006219,0.000000,0.000000,0.000000,0.000000,0.276110,0.421670,0.116427,0.530399,0.530820,0.621509,0.551950
35977,3597.0,2023,0.272013,0.274214,0.276414,0.278615,0.280816,0.283016,0.289751,0.336372,0.398651,0.467262,0.513826,0.525186,0.541286,0.560378,0.558251,0.545096,0.527368,0.512898,0.529027,0.537403,0.544167,0.549246,0.549436,0.544901,0.527620,0.503073,0.495203,0.451479,0.413602,0.396465,0.394225,0.396728,0.399145,0.0,0.000000,-0.000250,-0.001403,-0.001403,-0.005771,-0.000208,-0.000208,-0.000208,-0.000208,-0.000152,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314,0.003337,0.008810,0.008688,0.010523,0.002067,0.001518,0.004150,0.000467,-0.001145,-0.002159,-0.003543,0.000146,0.002569,0.000934,0.000832,0.000424,-0.000542,-0.000732,-0.004349,-0.001405,-0.001058,-0.011173,-0.002793,-0.001384,0.000025,0.000607,-0.000308,-0.000674,-0.001037,-0.001399,-0.000500,0.000000,0.000000,0.000000,0.0,0.000000,0.001811,0.003030,0.003030,0.012883,0.000449,0.000449,0.000449,0.000449,0.000363,0.000679,0.000679,0.000679,0.000679,0.000679,0.000679,0.000679,0.008867,0.019206,0.019053,0.022837,0.004721,0.003280,0.009118,0.001033,0.002525,0.004665,0.007678,0.001666,0.006341,0.002027,0.001799,0.001119,0.001361,0.001778,0.009556,0.003186,0.002286,0.024780,0.006034,0.003376,0.000054,0.001311,0.000913,0.001457,0.002276,0.003023,0.002212,0.000000,0.000000,0.000000,0.269587,0.406119,0.109484,0.501615,0.560853,0.631390,0.546351
35978,3597.0,2024,0.300335,0.295859,0.289639,0.280184,0.267577,0.267590,0.283698,0.324249,0.367936,0.393292,0.425212,0.469456,0.475025,0.476095,0.474376,0.469761,0.463085,0.456158,0.448001,0.445298,0.447925,0.450708,0.453220,0.460118,0.457763,0.438618,0.432123,0.409606,0.356704,0.321340,0.321372,0.321404,0.320621,0.0,0.000102,0.000102,0.000102,0.000102,0.000102,0.000102,0.000275,0.000709,-0.001120,-0.007742,-0.001447,-0.000452,-0.000889,-0.000889,-0.002776,-0.000464,0.001241,0.002969,0.008582,0.004563,0.002916,0.008217,0.002360,0.001334,0.000095,-0.000909,-0.000967,-0.000692,-0.000071,-0.002036,0.000310,0.000108,0.000511,0.000467,-0.000633,-0.000579,-0.002547,-0.002603,-0.002186,-0.011676,0.000005,0.000005,0.000005,-0.000471,-0.000946,-0.000946,-0.001209,-0.001315,0.000000,0.000000,0.000000,0.0,0.000220,0.000220,0.000220,0.000220,0.000220,0.000220,0.000664,0.001531,0.003162,0.017555,0.004180,0.000977,0.001920,0.001920,0.006353,0.001001,0.003011,0.006513,0.018723,0.009858,0.006300,0.018089,0.006640,0.003389,0.000641,0.002266,0.002134,0.001790,0.000681,0.004659,0.000679,0.000556,0.001132,0.001444,0.001906,0.002632,0.006090,0.006210,0.005599,0.025230,0.000010,0.000010,0.000010,0.001146,0.002043,0.002043,0.002619,0.002840,0.000000,0.000000,0.000000,0.180011,0.374891,0.067485,0.443813,0.742534,0.767080,0.578748
35979,3597.0,2025,0.289525,0.288845,0.294046,0.277406,0.267093,0.283658,0.311139,0.325802,0.338930,0.380254,0.418946,0.438006,0.444349,0.449089,0.453499,0.441671,0.434762,0.426779,0.416181,0.414407,0.409124,0.406500,0.408625,0.408706,0.408466,0.406736,0.404940,0.403031,0.402983,0.404196,0.404804,0.404606,0.405463,0.0,-0.000021,0.004387,0.002187,-0.000558,-0.000518,-0.000518,0.000745,0.000887,-0.000233,-0.000233,-0.000233,-0.000233,0.000323,0.000879,-0.004676,0.002227,0.002722,0.004554,0.001251,0.003436,0.008283,0.004878,0.001436,0.000524,0.001061,-0.000229,-0.002450,-0.000717,-0.002145,-0.000404,-0.000218,-0.001199,0.000578,0.000075,-0.000014,-0.000121,0.000135,-0.000793,-0.000130,0.000173,0.000173,-0.000028,-0.000028,0.000236,0.000236,0.000162,0.000133,0.000133,0.000133,0.000133,0.000133,0.0,0.000840,0.011326,0.005393,0.001210,0.001120,0.001120,0.002137,0.002287,0.000504,0.000504,0.000504,0.000504,0.000933,0.001899,0.010118,0.004811,0.005902,0.010446,0.002703,0.007572,0.018024,0.010587,0.003105,0.001132,0.002320,0.000727,0.005405,0.001609,0.004663,0.001017,0.000471,0.002683,0.001409,0.000173,0.000030,0.000397,0.000352,0.001791,0.000370,0.000374,0.000374,0.000061,0.000061,0.000509,0.000509,0.000354,0.000287,0.000287,0.000287,0.000287,0.000287,0.175497,0.366706,0.064356,0.428662,0.756069,0.773917,0.572626

In [9]:
df = df.merge(veg_agg, how = 'inner', on = 'plot_id')

In [11]:
# --- NDVI anomaly: plot deviation from vineyard mean per week × year ---
# Strips vintage effects, isolates the spatial (terroir) signal
ndvi_cols = [f'ndvi_smooth_mean_{w}' for w in range(36, 44)]
for col in ndvi_cols:
    yearly_mean = df.groupby('year')[col].transform('mean')
    df[f'ndvi_anomaly_{col.split("_")[-1]}'] = df[col] - yearly_mean

anomaly_cols = [f'ndvi_anomaly_{w}' for w in range(36, 44)]
print('Anomaly range:', df[anomaly_cols].min().min(), 'to', df[anomaly_cols].max().max())
print('Vineyard mean anomaly (should be ~0):', df[anomaly_cols].mean().mean())

Anomaly range: -0.411594403586821 to 0.40475673205779605
Vineyard mean anomaly (should be ~0): -1.4272560343147924e-17

In [12]:
df

,plot_id,curve_mean,curve_min,curve_max,pro_curve_mean,pro_curve_min,pro_curve_max,plan_curve_mean,plan_curve_min,plan_curve_max,elev_min,elev_max,elev_mean,elev_dev_min,elev_dev_max,elev_dev_mean,geometry,total_relief,area_m2,area_ha,aspect_min_cos,aspect_min_sin,aspect_max_cos,aspect_max_sin,aspect_mean_cos,aspect_mean_sin,slope_rad,slope_grad,slope_x,slope_y,year,ndvi_smooth_mean_13,ndvi_smooth_mean_14,ndvi_smooth_mean_15,ndvi_smooth_mean_16,ndvi_smooth_mean_17,ndvi_smooth_mean_18,ndvi_smooth_mean_19,ndvi_smooth_mean_20,ndvi_smooth_mean_21,ndvi_smooth_mean_22,ndvi_smooth_mean_23,ndvi_smooth_mean_24,ndvi_smooth_mean_25,ndvi_smooth_mean_26,ndvi_smooth_mean_27,ndvi_smooth_mean_28,ndvi_smooth_mean_29,ndvi_smooth_mean_30,ndvi_smooth_mean_31,ndvi_smooth_mean_32,ndvi_smooth_mean_33,ndvi_smooth_mean_34,ndvi_smooth_mean_35,ndvi_smooth_mean_36,ndvi_smooth_mean_37,ndvi_smooth_mean_38,ndvi_smooth_mean_39,ndvi_smooth_mean_40,ndvi_smooth_mean_41,ndvi_smooth_mean_42,ndvi_smooth_mean_43,ndvi_smooth_mean_44,ndvi_smooth_mean_45,ndvi_smooth_slope_1,ndvi_smooth_slope_2,ndvi_smooth_slope_3,ndvi_smooth_slope_4,ndvi_smooth_slope_5,ndvi_smooth_slope_6,ndvi_smooth_slope_7,ndvi_smooth_slope_8,ndvi_smooth_slope_9,ndvi_smooth_slope_10,ndvi_smooth_slope_11,ndvi_smooth_slope_12,ndvi_smooth_slope_13,ndvi_smooth_slope_14,ndvi_smooth_slope_15,ndvi_smooth_slope_16,ndvi_smooth_slope_17,ndvi_smooth_slope_18,ndvi_smooth_slope_19,ndvi_smooth_slope_20,ndvi_smooth_slope_21,ndvi_smooth_slope_22,ndvi_smooth_slope_23,ndvi_smooth_slope_24,ndvi_smooth_slope_25,ndvi_smooth_slope_26,ndvi_smooth_slope_27,ndvi_smooth_slope_28,ndvi_smooth_slope_29,ndvi_smooth_slope_30,ndvi_smooth_slope_31,ndvi_smooth_slope_32,ndvi_smooth_slope_33,ndvi_smooth_slope_34,ndvi_smooth_slope_35,ndvi_smooth_slope_36,ndvi_smooth_slope_37,ndvi_smooth_slope_38,ndvi_smooth_slope_39,ndvi_smooth_slope_40,ndvi_smooth_slope_41,ndvi_smooth_slope_42,ndvi_smooth_slope_43,ndvi_smooth_slope_44,ndvi_smooth_slope_45,ndvi_smooth_slope_46,ndvi_smooth_slope_47,ndvi_smooth_slope_48,ndvi_smooth_slope_49,ndvi_smooth_slope_50,ndvi_smooth_slope_51,ndvi_smooth_slope_52,ndvi_smooth_std_1,ndvi_smooth_std_2,ndvi_smooth_std_3,ndvi_smooth_std_4,ndvi_smooth_std_5,ndvi_smooth_std_6,ndvi_smooth_std_7,ndvi_smooth_std_8,ndvi_smooth_std_9,ndvi_smooth_std_10,ndvi_smooth_std_11,ndvi_smooth_std_12,ndvi_smooth_std_13,ndvi_smooth_std_14,ndvi_smooth_std_15,ndvi_smooth_std_16,ndvi_smooth_std_17,ndvi_smooth_std_18,ndvi_smooth_std_19,ndvi_smooth_std_20,ndvi_smooth_std_21,ndvi_smooth_std_22,ndvi_smooth_std_23,ndvi_smooth_std_24,ndvi_smooth_std_25,ndvi_smooth_std_26,ndvi_smooth_std_27,ndvi_smooth_std_28,ndvi_smooth_std_29,ndvi_smooth_std_30,ndvi_smooth_std_31,ndvi_smooth_std_32,ndvi_smooth_std_33,ndvi_smooth_std_34,ndvi_smooth_std_35,ndvi_smooth_std_36,ndvi_smooth_std_37,ndvi_smooth_std_38,ndvi_smooth_std_39,ndvi_smooth_std_40,ndvi_smooth_std_41,ndvi_smooth_std_42,ndvi_smooth_std_43,ndvi_smooth_std_44,ndvi_smooth_std_45,ndvi_smooth_std_46,ndvi_smooth_std_47,ndvi_smooth_std_48,ndvi_smooth_std_49,ndvi_smooth_std_50,ndvi_smooth_std_51,ndvi_smooth_std_52,ndvi_cov,ndvi_mean,ndvi_std,ndvi_mean_norm,ndvi_std_norm,ndvi_cov_norm,health,ndvi_anomaly_36,ndvi_anomaly_37,ndvi_anomaly_38,ndvi_anomaly_39,ndvi_anomaly_40,ndvi_anomaly_41,ndvi_anomaly_42,ndvi_anomaly_43
0,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,"POLYGON ((-119.78208 45.87245, -119.78215 45.8...",1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2016,0.417441,0.417741,0.415264,0.412015,0.410159,0.410159,0.408649,0.406006,0.403366,0.400812,0.398296,0.395780,0.393264,0.390748,0.388232,0.384497,0.373238,0.356197,0.348879,0.346145,0.345504,0.355702,0.381068,0.413351,0.438675,0.443236,0.440521,0.432348,0.424176,0.416003,0.407830,0.379300,0.366964,0.0,0.000000,0.000000,0.000000,0.000000,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,-0.000078,-0.000464,-0.000464,0.000000,0.000000,-0.000378,-0.000378,-0.000376,-0.000359,-0.000359,-0.000359,-0.000359,-0.000359,-0.000359,-0.001071,-0.001783,-0.001851,-0.000534,-0.000351,0.000406,0.003347,0.003689,0.005842,0.000652,0.000652,-0.001168,-0.001168,-0.001168,-0.001168,-0.001168,-0.008094,0.000948,0.000948,0.000948,0.001134,0.001319,0.001319,-0.005969,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000313,0.001003,0.001003,0.000000,0.000000,0.000816,0.000816,0.000811,0.000776,0.000776,0.000776,0.000776,0.000776,0.000776,0.002445,0.003851,0.004258,0.001196,0.000759,0.000913,0.007293,0.007969,0.012621,0.001408,0.001408,0.002522,0.002522,0.002522,0.002522,0.002522,0.018546,0.002048,0.002048,0.002048,0.002457,0.002850,0.002850,0.019600,0.000000,0.061211,0.399301,0.024442,0.488995,0.928728,0.947038,0.677199,-0.073815,-0.047348,-0.041802,-0.036708,-0.031953,-0.027198,-0.022443,-0.017688
1,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,"POLYGON ((-119.78208 45.87245, -119.78215 45.8...",1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2017,0.329644,0.330595,0.331926,0.333256,0.334587,0.338387,0.351077,0.364508,0.376660,0.385999,0.395252,0.404505,0.399311,0.355272,0.339719,0.331969,0.322669,0.320248,0.318124,0.322323,0.324225,0.321754,0.322187,0.327781,0.330168,0.331366,0.333434,0.339194,0.339164,0.338132,0.337109,0.336203,0.335328,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000014,0.000190,0.000190,0.000190,0.000190,0.001425,0.001919,0.001919,0.001386,0.001322,0.001322,0.001322,-0.003970,-0.004277,-0.000937,-0.001231,-0.000664,-0.000828,0.000356,0.000338,0.000090,-0.000614,0.001560,0.000333,0.000323,0.000109,0.000761,0.000437,-0.000147,-0.000147,-0.000141,-0.000125,-0.000125,-0.000125,-0.000275,-0.000650,-0.000046,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000190,0.000411,0.000411,0.000411,0.000411,0.003191,0.004145,0.004145,0.002999,0.002856,0.002856,0.002856,0.008904,0.009495,0.002024,0.002659,0.002196,0.001798,0.001029,0.000758,0.000448,0.001365,0.003402,0.000719,0.000713,0.000236,0.001703,0.001147,0.000319,0.000319,0.000305,0.000270,0.000270,0.000270,0.000647,0.001404,0.000650,0.000000,0.000000,0.000000,0.066718,0.341236,0.022767,0.381518,0.935975,0.938697,0.598005,-0.142266,-0.128436,-0.106456,-0.089132,-0.076720,-0.069060,-0.062112,-0.055108
2,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,"POLYGON ((-119.78208 45.87245, -119.78215 45.8...",1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2018,0.337342,0.339505,0.341668,0.343619,0.344173,0.345555,0.346938,0.343668,0.341470,0.332540,0.330672,0.330827,0.320533,0.319656,0.314177,0.313716,0.306276,0.305823,0.303524,0.306111,0.314969,0.329831,0.339823,0.344996,0.351547,0.354465,0.366220,0.378805,0.389178,0.428417,0.467546,0.480323,0.492458,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000671,0.001297,0.000309,0.000309,0.000309,0.000309,0.000167,0.000197,0.000197,0.000197,-0.000371,-0.000499,-0.001485,0.000213,-0.000566,-0.000727,-0.000688,-0.000402,-0.000188,-0.001330,-0.000526,0.000361,0.000039,0.002017,0.002040,0.000333,0.001936,0.000417,0.000417,0.003317,0.001256,0.002308,0.008811,0.001145,0.003129,0.001009,0.001136,-0.003627,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001467,0.002802,0.000668,0.000668,0.000668,0.000668,0.000435,0.000427,0.000427,0.000427,0.000943,0.001097,0.003556,0.000460,0.001499,0.002002,0.001735,0.000936,0.000503,0.003396,0.001362,0.001030,0.000733,0.004407,0.004407,0.000907,0.004447,0.000901,0.000901,0.007535,0.002714,0.005300,0.019070,0.002474,0.006792,0.002209,0.002454,0.010856,0.000000,0.000000,0.000000,0.000000,0.000000,0.153744,0.355367,0.054636,0.407674,0.798117,0.806869,0.571971,-0.119758,-0.111295,-0.106242,-0.089821,-0.072075,-0.056171,0.018308,0.098746
3,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,"POLYGON ((-119.78208 45.87245, -119.78215 45.8...",1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2019,0.420147,0.417991,0.417286,0.416581,0.415876,0.414144,0.390046,0.377250,0.367943,0.333504,0.307616,0.298621,0.277066,0.268343,0.257594,0.253854,0.250562,0.249726,0.247150,0.253554,0.258864,0.258951,0.259078,0.258787,0.258504,0.259266,0.260198,0.260873,0.258438,0.255991,0.253653,0.256494,0.299480,0.0,-0.000042,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000569,-0.000935,-0.000584,-0.000101,-0.000101,-0.000101,-0.000101,-0.001171,-0.003517,-0.001153,-0.002081,-0.003267,-0.001364,-0.002576,-0.002017,-0.002022,-0.001092,-0.000099,-0.000736,0.000314,0.000672,0.000888,0.000297,0.000071,0.000183,-0.000065,0.000034,0.000133,0.000133,-0.000015,-0.000440,-0.000320,-0.000360,0.004201,0.004435,0.002910,0.002761,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000300,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.003862,0.002245,0.001262,0.000218,0.000218,0.000218,0.000218,0.003792,0.007767,0.002490,0.005189,0.007391,0.003863,0.005726,0.005762,0.004371,0.002362,0.000237,0.001595,0.001161,0.001979,0.001919,0.001101,0.000213,0.000487,0.000139,0.000133,0.000287,0.000287,0.000209,0.000959,0.000692,0.000778,0.010231,0.009920,0.006288,0.005965,0.000000,0.000000,0.000000,0.000000,0.000000,0.239423,0.338190,0.080971,0.375880,0.684197,0.677082,0.505802,-0.178223,-0.171176,-0.164196,-0.157226,-0.140817,-0.106719,-0.090181,-0.070564
4,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,"POLYGON ((-119.78208 45.87245, -119.78215 45.8...",1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2020,0.426042,0.420337,0.406763,0.355260,0.309138,0.300667,0.286758,0.282486,0.283371,0.281487,0.275424,0.276846,0.277771,0.275635,0.272246,0.251884,0.244928,0.250605,0.256064,0.264572,0.270360,0.275373,0.277629,0.290302,0.300525,0.303298,0.305589,0.309173,0.300149,0.297698,0.296588,0.295123,0.298194,0.0,0.000000,0.000000,0.000000,0.000000,0.003504,0.006519,-0.000644,-0.002138,-0.000858,-0.000820,-0.000815,-0.000815,-0.000815,-0.005405,-0.010096,-0.001210,-0.001210,-0.002390,0.000126,0.000126,-0.001271,0.000203,0.000203,-0.000086,-0.000376,-0.000880,-0.004101,-0.000571,0.001412,0.000533,0.000191,0.000983,-0.000812,0.001257,0.003374,0.000320,0.000406,0.000286,0.000719,-0.000983,-0.000159,-0.000159,-0.000324,0.000889,0.000889,0.000919,0.001281,0.002587,0.001490,0.001490,0.000106,0.0,0.000000,0.000000,0.000000,0.000000,0.007570,0.014232,0.010650,0.004834,0.001853,0.001771,0.001761,0.001761,0.001761,0.012744,0.023066,0.002614,0.002614,0.005443,0.000273,0.000273,0.002915,0.000439,0.000439,0.000372,0.000812,0.002088,0.009112,0.002349,0.003092,0.002348,0.001516,0.002154,0.002428,0.002928,0.007347,0.000713,0.000878,0.000618,0.001700,0.002553,0.000342,0.000342,0.000808,0.001921,0.001921,0.001986,0.002883,0.005721,0.003218,0.003218,0.001490,0.193982,0.325241,0.063091,0.351912,0.761540,0.745916,0.515006,-0.082830,-0.057153,-0.051433,-0.044712,-0.031475,-0.010075,-0.001416,0.002637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35975,3597,-0.000758,-0.019660,0.016977,0.001952,-0.012836,0.017013,-0.000758,-0.019660,0.016977,232.254944,235.135742,233.620047,47.291107,50.171906,48.656196,"POLYGON ((-119.77612 45.87557, -119.77618 45.8...",2.880798,940.121044,0.094012,-0.667735,0.744399,-0.958729,-0.284322,-0.945427,0.325835,0.083309,0.083502,-0.078945,0.027208,2021,0.260427,0.254365,0.238068,0.243177,0.258024,0.269298,0.281962,0.303152,0.312652,0.337048,0.349271,0.367689,0.385405,0.395900,0.393201,0.389211,0.383006,0.382267,0.381121,0.384151,0.393474,0.398543,0.404984,0.412823,0.412136,0.406469,0.396026,0.382007,0.375481,0.346197,0.340742,0.336458,0.332479,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000295,-0.001003,-0.001538,-0.001078,-0.000786,-0.001236,-0.003111,0.003419,0.001700,0.001543,0.002783,0.001287,0.001658,0.003462,0.001180,0.003152,0.001914,0.000365,-0.000454,-0.000880,-0.000297,-0.000089,-0.000226,0.001517,0.001354,-0.000290,0.001476,0.000050,-0.000759,-0.000988,-0.001916,-0.001027,-0.002268,-0.001490,-0.000612,-0.000612,-0.000383,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002200,0.002173,0.003322,0.002334,0.001701,0.002792,0.006817,0.007630,0.003672,0.003334,0.006374,0.002779,0.003727,0.007875,0.002549,0.006851,0.004136,0.001316,0.001253,0.001907,0.001071,0.000191,0.000524,0.003531,0.002960,0.001357,0.003245,0.000191,0.001687,0.002175,0.004174,0.002499,0.005691,0.004046,0.001322,0.001322,0.001145,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.166675,0.339790,0.056634,0.378842,0.789470,0.787282,0.546506,-0.012282,-0.009201,-0.012769,-0.015471,-0.020405,-0.016449,-0.018558,-0.019373
35976,3597,-0.000758,-0.019660,0.016977,0.001952,-0.012836,0.017013,-0.000758,-0.019660,0.016977,232.254944,235.135742,233.620047,47.291107,50.171906,48.656196,"POLYGON ((-119.77612 45.87557, -119.77618 45.8...",2.880798,940.121044,0.094012,-0.667735,0.744399,-0.958729,-0.284322,-0.945427,0.325835,0.083309,0.083502,-0.078945,0.027208,2022,0.273234,0.282769,0.299788,0.317859,0.340028,0.362378,0.381280,0.396742,0.405271,0.413589,0.421907,0.436211,0.482206,0.556552,0.575809,0.595833,0.596200,0.578534,0.573135,0.565441,0.565494,0.559885,0.558400,0.553192,0.558149,0.560238,0.555497,0.526853,0.504118,0.482449,0.461605,0.443183,0.433803,0.0,-0.000617,-0.000617,-0.000617,-0.000617,-0.001793,-0.002065,0.000137,0.000150,0.000254,0.000254,0.000254,0.000410,0.002119,0.002533,0.002760,0.003330,0.002851,0.002659,0.001346,0.001188,0.001188,0.001188,0.004680,0.005997,0.006510,0.002069,0.002524,-0.003017,-0.000683,-0.001046,-0.000590,-0.000223,-0.000601,-0.000334,-0.000414,0.001284,-0.000359,-0.002051,-0.005354,-0.002417,-0.002735,-0.004635,-0.001340,-0.001340,-0.002604,-0.004022,-0.002078,0.000000,0.000000,0.000000,0.000000,0.0,0.001333,0.001333,0.001333,0.001333,0.003892,0.005833,0.000296,0.000325,0.000550,0.000550,0.000550,0.000986,0.004600,0.005471,0.005976,0.007193,0.006167,0.005744,0.002941,0.002567,0.002567,0.002567,0.010830,0.012976,0.015745,0.004665,0.005471,0.006645,0.001748,0.002318,0.001439,0.001081,0.001445,0.000960,0.001327,0.002839,0.000932,0.004474,0.011930,0.005222,0.006028,0.010198,0.002895,0.002895,0.006027,0.008769,0.006219,0.000000,0.000000,0.000000,0.000000,0.276110,0.421670,0.116427,0.530399,0.530820,0.621509,0.551950,0.012358,0.016880,0.024752,0.026642,0.014380,0.000409,0.002835,0.005469
35977,3597,-0.000758,-0.019660,0.016977,0.001952,-0.012836,0.017013,-0.000758,-0.019660,0.016977,232.254944,235.135742,233.620047,47.291107,50.171906,48.656196,"POLYGON ((-119.77612 45.87557, -119.77618 45.8...",2.880798,940.121044,0.094012,-0.667735,0.744399,-0.958729,-0.284322,-0.945427,0.325835,0.083309,0.083502,-0.078945,0.027208,2023,0.272013,0.274214,0.276414,0.278615,0.280816,0.283016,0.289751,0.336372,0.398651,0.467262,0.513826,0.525186,0.541286,0.560378,0.558251,0.545096,0.527368,0.512898,0.529027,0.537403,0.544167,0.549246,0.549436,0.544901,0.527620,0.503073,0.495203,0.451479,0.413602,0.396465,0.394225,0.396728,0.399145,0.0,0.000000,-0.000250,-0.001403,-0.001403,-0.005771,-0.000208,-0.000208,-0.000208,-0.000208,-0.000152,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314,0.003337,0.008810,0.008688,0.010523,0.002067,0.001518,0.004150,0.000467,-0.001145,-0.002159,-0.003543,0.000146,0.002569,0.000934,0.000832,0.000424,-0.000542,-0.000732,-0.004349,-0.001405,-0.001058,-0.011173,-0.002793,-0.001384,0.000025,0.000607,-0.000308,-0.000674,-0.001037,-0.001399,-0.000500,0.000000,0.000000,0.000000,0.0,0.000000,0.001811,0.003030,0.003030,0.012883,0.000449,0.000449,0.000449,0.000449,0.000363,0.000679,0.000679,0.000679,0.000679,0.000679,0.000679,0.000679,0.008867,0.019206,0.019053,0.022837,0.004721,0.003280,0.009118,0.001033,0.002525,0.004665,0.007678,0.001666,0.006341,0.002027,0.001799,0.001119,0.001361,0.001778,0.009556,0.003186,0.002286,0.024780,0.006034,0.003376,0.000054,0.001311,0.000913,0.001457,0.002276,0.003023,0.002212,0.000000,0.000000,0.000000,0.269587,0.406119,0.109484,0.501615,0.560853,0.631390,0.546351,0.038465,0.028875,0.015331,0.011632,-0.004642,-0.019134,-0.024905,-0.016574
35978,3597,-0.000758,-0.019660,0.016977,0.001952,-0.012836,0.017013,-0.000758,-0.019660,0.016977,232.254944,235.135742,233.620047,47.291107,50.171906,48.656196,"POLYGON ((-119.77612 45.87557, -119.77618 45.8...",2.880798,940.121044,0.094012,-0.667735,0.744399,-0.958729,-0.284322,-0.945427,0.325835,0.083309,0.083502,-0.078945,0.027208,2024,0.300335,0.295859,0.289639,0.280184,0.267577,0.267590,0.283698,0.324249,0.367936,0.393292,0.425212,0.469456,0.475025,0.476095,0.474376,0.469761,0.463085,0.456158,0.448001,0.445298,0.447925,0.450708,0.453220,0.460118,0.457763,0.438618,0.432123,0.409606,0.356704,0.321340,0.321372,0.321404,0.320621,0.0,0.000102,0.000102,0.000102,0.000102,0.000102,0.000102,0.000275,0.000709,-0.001120,-0.007742,-0.001447,-0.000452,-0.000889,-0.000889,-0.002776,-0.000464,0.001241,0.002969,0.008582,0.004563,0.002916,0.008217,0.002360,0.001334,0.000095,-0.000909,-0.000967,-0.000692,-0.000071,-0.002036,0.000310,0.000108,0.000511,0.000467,-0.000633,-0.000579,-0.002547,-0.002603,-0.002186,-0.011676,0.000005,0.000005,0.000005,-0.000471,-0.000946,-0.000946,-0.001209,-0.001315,0.000000,0.000000,0.000000,0.0,0.000220,0.000220,0.000220,0.000220,0.000220,0.000220,0.000664,0.001531,0.003162,0.017555,0.004180,0.000977,0.001920,0.001920,0.006353,0.001001,0.003011,0.006513,0.018723,0.009858,0.006300,0.018089,0.006640,0.003389,0.000641,0.002266,0.002134,0.001790,0.000681,0.004659,0.000679,0.000556,0.001132,0.001444,0.001906,0.002632,0.006090,0.006210,0.005599,0.025230,0.000010,0.000010,0.000010,0.001146,0.002043,0.002043,0.002619,0.002840,0.000000,0.000000,0.000000,0.180011,0.374891,0.067485,0.443813,0.742534,0.767080,0.578748,0.027626,0.027117,0.018188,0.014922,0.006245,0.000043,-0.013085,-0.009546

### Now let's add some weather information

First load the wather that has been unzipped and clipped to the vineyard

In [13]:
weather = pd.read_pickle('../data/PRISM/df.pkl')

weather = (
    weather
    .groupby("date", as_index=False)
    .first()
)

weather['date'] = pd.to_datetime(weather['date'])
weather['doy'] = weather['date'].dt.dayofyear
weather['year'] = weather['date'].dt.year

weather

,date,ppt,tmax,tmean,tmin,vpdmax,vpdmin,doy,year
0,2016-01-01,0.000000,-4.994952,-6.205034,-7.415116,1.100000,0.440088,1,2016
1,2016-01-02,0.000000,-5.805048,-7.305048,-8.805048,0.700000,0.727885,2,2016
2,2016-01-03,1.000000,-5.505030,-6.977509,-8.449988,0.000000,0.644641,3,2016
3,2016-01-04,0.000000,-3.160078,-4.837600,-6.515122,0.000000,0.000000,4,2016
4,2016-01-05,0.455039,-1.105036,-2.687591,-4.270146,0.000000,0.000000,5,2016
...,...,...,...,...,...,...,...,...,...
3648,2025-12-27,0.000000,6.105038,2.199998,-1.705042,1.800000,0.066595,361,2025
3649,2025-12-28,0.000000,4.950006,0.622482,-3.705042,1.755039,0.000000,362,2025
3650,2025-12-29,0.000000,5.749994,0.949991,-3.850012,2.200000,0.112112,363,2025
3651,2025-12-30,0.000000,4.249994,-0.322484,-4.894962,1.600000,0.000000,364,2025
3652,2025-12-31,0.000000,-0.805048,-3.394969,-5.984890,0.000000,0.000000,365,2025

### Crack at some frost and growing degree days cumulative per month

In [14]:
# Compute frost days and GDD
weather['frost'] = (weather['tmin'] < 0)
weather['gdd'] = (weather['tmean'] - 10).clip(lower=0)

In [15]:
# Compute cumulative GDD for each month
weather['week'] = weather['date'].dt.week
cumulative_gdd = weather.groupby([ 'year', 'week'])['gdd'].sum().groupby(level=[0,1]).cumsum()
# Reset index to turn MultiIndex into columns
cumulative_gdd = cumulative_gdd.rename('cumulative_gdd').reset_index()

# Merge back to weather
weather = weather.merge(
    cumulative_gdd,
    on=['year', 'week'],
    how='left'
)


weather

/home/simonhans/anaconda3/envs/GrapeExpectations/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.

,date,ppt,tmax,tmean,tmin,vpdmax,vpdmin,doy,year,frost,gdd,week,cumulative_gdd
0,2016-01-01,0.000000,-4.994952,-6.205034,-7.415116,1.100000,0.440088,1,2016,True,0.0,53,0.0
1,2016-01-02,0.000000,-5.805048,-7.305048,-8.805048,0.700000,0.727885,2,2016,True,0.0,53,0.0
2,2016-01-03,1.000000,-5.505030,-6.977509,-8.449988,0.000000,0.644641,3,2016,True,0.0,53,0.0
3,2016-01-04,0.000000,-3.160078,-4.837600,-6.515122,0.000000,0.000000,4,2016,True,0.0,1,0.0
4,2016-01-05,0.455039,-1.105036,-2.687591,-4.270146,0.000000,0.000000,5,2016,True,0.0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3648,2025-12-27,0.000000,6.105038,2.199998,-1.705042,1.800000,0.066595,361,2025,True,0.0,52,0.0
3649,2025-12-28,0.000000,4.950006,0.622482,-3.705042,1.755039,0.000000,362,2025,True,0.0,52,0.0
3650,2025-12-29,0.000000,5.749994,0.949991,-3.850012,2.200000,0.112112,363,2025,True,0.0,1,0.0
3651,2025-12-30,0.000000,4.249994,-0.322484,-4.894962,1.600000,0.000000,364,2025,True,0.0,1,0.0
3652,2025-12-31,0.000000,-0.805048,-3.394969,-5.984890,0.000000,0.000000,365,2025,True,0.0,1,0.0

In [16]:
weather = weather[
    (weather['week'] > 27) &
    (weather['week'] < 44)
].copy()

In [17]:
# Define which aggregations to use
agg_funcs = {
    'ppt': 'sum',
    'tmax': 'max',
    'tmin': 'min',
    'tmean': 'mean',
    'vpdmax': 'max',
    'vpdmin': 'min',
    'cumulative_gdd': 'max'
}

# Aggregate to long-form first (year, week, variables)
weekly_long = weather.groupby(['year','week']).agg(agg_funcs).reset_index()

# Pivot to wide form (one row per year, columns per week)
weekly_wide = pd.DataFrame({'year': weekly_long['year'].unique()})

for col in ['ppt','tmax','tmin','tmean','vpdmax','vpdmin','cumulative_gdd']:
    pivoted = weekly_long.pivot(index='year', columns='week', values=col)
    # Rename columns to include variable name
    pivoted.columns = [f'{col}_{w}' for w in pivoted.columns]
    weekly_wide = weekly_wide.merge(pivoted, on='year', how='left')

weekly_wide.reset_index(drop=True, inplace=True)

In [18]:
weekly_wide

,year,ppt_28,ppt_29,ppt_30,ppt_31,ppt_32,ppt_33,ppt_34,ppt_35,ppt_36,ppt_37,ppt_38,ppt_39,ppt_40,ppt_41,ppt_42,ppt_43,tmax_28,tmax_29,tmax_30,tmax_31,tmax_32,tmax_33,tmax_34,tmax_35,tmax_36,tmax_37,tmax_38,tmax_39,tmax_40,tmax_41,tmax_42,tmax_43,tmin_28,tmin_29,tmin_30,tmin_31,tmin_32,tmin_33,tmin_34,tmin_35,tmin_36,tmin_37,tmin_38,tmin_39,tmin_40,tmin_41,tmin_42,tmin_43,tmean_28,tmean_29,tmean_30,tmean_31,tmean_32,tmean_33,tmean_34,tmean_35,tmean_36,tmean_37,tmean_38,tmean_39,tmean_40,tmean_41,tmean_42,tmean_43,vpdmax_28,vpdmax_29,vpdmax_30,vpdmax_31,vpdmax_32,vpdmax_33,vpdmax_34,vpdmax_35,vpdmax_36,vpdmax_37,vpdmax_38,vpdmax_39,vpdmax_40,vpdmax_41,vpdmax_42,vpdmax_43,vpdmin_28,vpdmin_29,vpdmin_30,vpdmin_31,vpdmin_32,vpdmin_33,vpdmin_34,vpdmin_35,vpdmin_36,vpdmin_37,vpdmin_38,vpdmin_39,vpdmin_40,vpdmin_41,vpdmin_42,vpdmin_43,cumulative_gdd_28,cumulative_gdd_29,cumulative_gdd_30,cumulative_gdd_31,cumulative_gdd_32,cumulative_gdd_33,cumulative_gdd_34,cumulative_gdd_35,cumulative_gdd_36,cumulative_gdd_37,cumulative_gdd_38,cumulative_gdd_39,cumulative_gdd_40,cumulative_gdd_41,cumulative_gdd_42,cumulative_gdd_43
0,2016,0.000000,1.310078,0.000000,0.0,1.365116,0.000000,0.000000,0.00000,5.789922,1.385271,0.000000,0.000000,6.185271,18.615504,4.020155,21.570543,33.639926,36.139926,38.774818,35.305036,36.529842,36.739916,32.894964,33.339922,32.194952,31.160080,27.194952,29.350000,24.050012,20.305036,17.494970,17.774818,13.105038,13.294958,12.884886,11.474800,12.384886,12.429836,10.639926,7.760072,7.615116,4.370156,5.594962,6.115116,6.460084,0.205030,2.794958,4.550012,21.944242,22.429568,26.234941,21.894516,22.867052,24.830620,21.519602,19.065004,18.032170,17.391863,14.584660,17.102157,14.042137,10.906034,10.615336,10.066391,23.099999,24.934884,34.349613,26.010077,27.969767,29.644962,23.610076,23.644960,19.455039,15.065116,12.200000,15.810078,7.844961,7.444961,5.655039,4.700000,1.881505,1.950429,5.053060,1.712215,0.265490,4.835625,2.866083,0.850186,0.000000,0.000000,0.000000,1.087746,0.000000,0.000000,0.0,0.0,83.609693,87.006976,113.644589,83.261614,90.069361,103.814337,80.637215,63.455025,56.225192,51.743038,32.092622,49.715100,28.294959,10.842245,5.222467,5.369773
1,2017,0.000000,0.000000,0.000000,0.0,1.955039,0.000000,0.000000,0.00000,0.000000,0.644961,3.500000,0.165116,0.000000,1.220155,23.010078,0.000000,34.539920,37.739916,36.450006,38.194952,38.850000,33.994970,34.149988,36.694952,32.460084,33.705030,22.905042,28.394964,23.694952,17.784880,21.394964,20.294958,11.729854,11.294958,14.050012,14.950006,12.950006,10.539920,9.739916,13.560074,11.215122,5.860078,3.515110,8.394964,2.305036,-0.815110,0.015110,1.994970,23.469933,23.499556,25.381009,26.465334,26.314228,21.716722,21.802823,24.371096,22.391474,17.965728,13.128242,16.541088,12.202159,8.616778,11.253931,10.224969,25.044961,28.244961,29.900000,32.355039,33.810078,23.044961,26.310078,30.200000,23.975194,23.320154,9.610078,14.355039,12.800000,7.955039,9.120155,6.044961,1.874487,3.739983,5.032998,6.032692,0.000000,2.920158,0.000000,4.213529,0.000000,2.647971,0.000000,0.157001,0.367370,0.000000,0.0,0.0,94.289530,94.496891,107.667065,115.257339,114.199593,82.017053,82.619761,100.597675,86.740318,55.760098,21.897693,45.787616,15.415114,0.932563,9.050005,3.857346
2,2018,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.555039,0.00000,0.000000,0.000000,0.000000,0.000000,8.930232,9.785271,0.000000,1.410078,38.839922,38.284880,38.360078,39.005048,39.294958,36.484878,32.894964,32.894964,33.415120,25.249994,25.094962,27.794958,23.484878,21.484878,18.994970,19.615116,13.094962,11.950006,12.715122,12.229854,12.474800,12.139926,10.384886,9.360078,10.094962,6.460084,5.505048,4.450006,3.249994,0.705030,0.160080,2.105038,24.413899,24.148504,26.583888,24.722038,25.505977,23.633835,20.749946,19.454266,20.178242,16.018936,14.948948,15.640699,11.288924,10.804261,9.663566,12.058583,32.844961,34.579845,32.920155,34.775194,35.189922,30.114729,22.744961,21.355040,22.575194,12.275194,13.410078,17.655039,11.655038,8.944961,8.400000,6.555039,2.517418,4.326097,6.058558,0.639583,2.014639,3.275336,1.746291,0.000000,2.203734,0.000000,0.050233,0.521719,0.000000,0.000000,0.0,0.0,100.897294,99.039528,116.087214,103.054268,108.541839,95.436842,75.249619,66.179861,71.247694,42.132552,34.642637,39.484894,10.655033,6.839914,0.650003,14.760087
3,2019,0.000000,0.275194,1.410077,0.0,4.934884,0.000000,1.865116,0.00000,0.000000,3.134884,3.860465,0.220155,0.000000,0.000000,8.140310,0.000000,32.749994,32.694952,36.294958,35.639926,38.749994,32.594962,34.439928,34.494970,32.450006,28.660080,25.550012,26.850000,21.039920,24.394964,17.794958,22.205030,13.039920,10.405042,10.905042,12.484878,14.284880,12.739916,11.929836,11.284880,12.950006,9.950006,9.994970,3.850000,-0.394962,-3.294970,2.105038,-2.705042,23.203876,21.364951,23.107088,23.998835,24.574583,22.781341,22.389922,23.492469,22.706091,19.053934,16.770708,13.956422,10.554982,8.180011,10.715007,10.228627,19.820155,23.199999,29.300001,24.810078,31.910078,21.644962,23.434883,25.055039,20.275194,14.020155,9.910078,10.855039,9.955039,11.300000,6.744961,8.555039,2.356615,1.404485,2.935186,1.409238,0.000000,1.507120,0.000000,1.690513,1.845356,0.000000,0.000000,0.000000,0.545450,0.076900,0.0,0.0,92.427133,79.554654,91.749617,97.991846,102.022084,89.469386,86.729455,94.447280,88.942635,63.377537,47.394958,31.512397,9.944949,5.132562,6.907365,9.197660
4,2020,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.455039,0.000000,8.420155,33.339922,35.284880,38.684890,41.160080,35.439928,37.184890,38.149988,32.439928,34.805036,29.705030,25.605038,26.294958,29.339922,28.194952,22.439928,19.684890,12.484878,11.139926,11.884886,14.294958,10.329844,10.594962,11.784880,10.925182,12.415120,6.894964,9.405042,6.915120,6.215122,8.850000,2.705030,-6.305048,21.344574,23.239592,24.357807,27.849555,22.045293,22.724586,25.249556,21.474252,23.552160,17.010410,17.003267,17.301108,17.411408,17.154263,13.678186,6.214672,24.144962,26.889923,33.779845,39.220156,27.889922,31.579846,30.655038,23.644960,26.365116,20.720154,10.520155,12.110078,16.744961,16.100000,8.600000,5.465116,2.910687,2.565012,4.508854,7.116609,0.728850,4.287842,1.428604,5.589854,5.110907,4.362866,0.000000,0.000000,0.481956,2.166800,0.0,0.0,79.412015,92.677142,100.504648,124.946887,84.317049,89.072104,106.746890,80.319763,94.865119,49.072873,49.022871,51.107758,51.879856,50.079841,26.097303,4.522478
5,2021,0.000000,0.000000,0.000000,0.0,0.000000,0.500000,0.000000,0.00000,6.710078,1.000000,0.000000,6.355039,0.000000,1.355039,17.285271,1.300000,38.050012,37.339922,40.515110,39.160080,38.539920,37.284880,31.884886,33.639926,33.539920,28.550012,31.584884,26.994970,23.529842,21.194952,21.539920,20.350000,15.619770,11.894964,16.574806,13.149988,12.174812,10.084884,8.574806,6.939928,11.084884,6.550012,5.794958,5.184890,2.594962,0.749994,2.629848,0.105038,25.968828,23.972756,27.271704,26.059911,26.607033,21.450941,19.883444,18.714563,20.434607,16.277134,18.031729,15.115673,12.549225,11.129958,12.454928,11.033553,34.689923,30.834883,39.785273,33.630233,34.414729,33.059689,20.434883,22.179845,24.889923,16.000000,20.100000,12.444961,11.679845,8.900000,9.644961,6.610078,5.732431,2.577344,5.757141,1.210265,2.060422,0.000000,1.089432,1.058243,0.000000,0.326663,0.000000,0.000000,0.401856,0.016188,0.0,0.0,111.781794,97.809291,120.901931,112.419376,116.249234,80.156587,69.184105,61.001939,73.042250,43.939939,56.222104,35.809708,17.844572,10.409701,17.184493,13.834867
6,2022,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,6.044961,0.000000,0.000000,0.000000,0.000000,12.885271,0.300000,36.684890,37.574806,42.474800,37.484878,38.694952,39.129848,36.249994,37.884886,33.950006,26.794958,28.749994,29.739916,29.794958,29.450006,23.149988,19.705030,13.639926,12.850000,16.205030,11.384886,13.339922,13.729854,11.284880,11.994970,9.439928,7.450006,8.984878,9.639926,8.139926,5.194952,3.605038,4.929836,24.482339,24.618439,29.789920,24.236988,25.501660,26.854156,24.868824,24.275637,20.352827,17.676024,18.169934,18.968546,18.594243,15.925308,11.931061,11.758525,25.714728,33.024806,41.204651,29.104651,34.000001,33.569767,27.069768,30.624806,24.410078,13.044961,15.244961,17.144962,16.144961,17.200000,10.500000,7.500000,1.868815,2.839170,5.488697,2.055610,0.629894,3.296071,0.070166,2.483680,2.598151,0.000000,0.000000,0.000000,1.379400,0.913367,0.0,0.0,101.376370,102.329070,138.529443,99.658913,108.511623,117.979094,104.081765,99.929461,72.469792,53.732166,57.189540,62.779819,60.159699,41.477153,13.517429,12.309676
7,2023,2.789923,0.000000,0.000000,0.0,0.300000,0.000000,1.389923,3.14031,0.000000,0.000000,3.479845,3.189923,3.855039,3.455039,0.000000,10.020155,38.519764,38.574806,34.439928,35.694952,36.284880,41.139926,36.084884,39.064728,31.594962,31.339922,25.705030,22.194952,26.139926,24.239916,24.184890,17.884886,14.309691,13.550012,12.729854,13.584884,13.764727,12.784880,10.329844,13.774818,8.729854,9.774818,7.384886,5.729854,6.174812,4.784880,4.529842,-3.994952,25.354821,25.454153,23.488429,24.246290,23.933441,25.995239,21.810630,21.850279,19.474199,20.849172,14.772867,14.404595,16.890589,13.937763,13.616721,6.098893,35.629458,35.604651,26.324806,30.189922,26.644962,36.834884,24.879845,30.929458,20.534883,23.534883,13.310078,9.744961,10.889923,10.644961,12.489922,5.144961,3.215572,4.183310,2.903834,4.752027,0.565385,4.074002,0.235181,0.000000,0.121607,0.920380,0.000000,0.000000,0.000000,0.000000,0.0,0.0,107.483747,108.179068,94.419006,99.724033,97.534089,111.966674,82.674413,82.951951,66.319393,75.944207,33.410068,30.832166,48.234125,27.564339,25.317049,1.239924
8,2024,0.000000,0.720155,0.000000,0.0,0.000000,0.000000,0.000000,0.00000,0.555039,1.914729,0.000000,0.000000,0.000000,0.000000,3.400000,1.010078,40.894964,37.839922,33.984878,40.405042,36.694952,34.239916,30.829844,34.805036,34.550012,32.805036,28.939928,31.394964,26.749994,27.350000,26.105038,18.429836,16.629848,16.694952,10.350000,15.629848,14.494970,12.574806,8.539920,6.649988,13.050012,10.129848,6.905042,4.460084,2.405042,4.084884,1.639926,-1.060072,27.800995,27.188816,21.996678,26.307751,25.598504,21.839147,19.523478,19.603212,23.600333,19.397120,17.087819,18.664949,12.451052,13.637099,13.441032,8.972813,36.865117,33.544960,24.824806,34.210078,26.944962,21.144960,18.024806,27.620155,27.155039,22.500000,17.244961,15.355038,16.300000,14.155038,11.165116,6.889922,6.282616,6.811549,0.000000,0.632556,4.910602,0.503720,0.000000,0.000000,2.289264,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,124.606967,120.321709,83.976745,114.154259,109.189530,82.874026,66.664345,67.222482,95.202334,65.779838,49.614733,60.654645,17.257362,25.459692,26.507373,3.602322
9,2025,0.000000,1.410077,1.575194,0.0,0.000000,1.834884,0.440310,0.00000,0.000000,7.389922,1.510078,0.000000,1.589923,6.879845,5.320155,6.695349,38.139926,35.139926,34.694952,37.439928,36.149988,38.339922,37.450006,35.450006,36.405042,31.305036,32.450006,30.094962,23.505048,24.594962,19.639926,18.905042,14.184890,15.249994,14.139926,15.594962,10.574806,15.374794,12.184890,15.450006,15.839922,10.384886,8.050012,6.805036,3.950006,2.860078,0.215122,1.405042,25.929567,24.184220,23.940973,25.643463,22.098117,25.402768,23.950997,25.099614,25.170321,20.991416,19.561075,17.300003,15.160685,13.576743,8.974640,9.546401,31.410079,27.500000,25.489922,30.889922,25.210077,29.910078,32.520155,27.310078,28.910079,17.820155,19.510078,18.300000,10.500000,12.500000,7.144961,6.565116,2.246026,3.832590,1.214396,2.919550,0.000000,0.000000,3.190715,2.336567,4.080479,0.000000,0.000000,0.000000,0.000000,1.254380,0.0,0.0,111.506970,99.289537,97.586813,109.504243,84.686819,107.819378,97.656979,105.697297,106.192249,76.939913,66.927525,51.100018,36.124795,25.037201,2.602321,2.132560

### Now we can combine data.

In [19]:
df['year'] = df['year'].astype(int)
df = pd.merge(df, weekly_wide, how = 'inner', on = 'year')

In [20]:
df

,plot_id,curve_mean,curve_min,curve_max,pro_curve_mean,pro_curve_min,pro_curve_max,plan_curve_mean,plan_curve_min,plan_curve_max,elev_min,elev_max,elev_mean,elev_dev_min,elev_dev_max,elev_dev_mean,geometry,total_relief,area_m2,area_ha,aspect_min_cos,aspect_min_sin,aspect_max_cos,aspect_max_sin,aspect_mean_cos,aspect_mean_sin,slope_rad,slope_grad,slope_x,slope_y,year,ndvi_smooth_mean_13,ndvi_smooth_mean_14,ndvi_smooth_mean_15,ndvi_smooth_mean_16,ndvi_smooth_mean_17,ndvi_smooth_mean_18,ndvi_smooth_mean_19,ndvi_smooth_mean_20,ndvi_smooth_mean_21,ndvi_smooth_mean_22,ndvi_smooth_mean_23,ndvi_smooth_mean_24,ndvi_smooth_mean_25,ndvi_smooth_mean_26,ndvi_smooth_mean_27,ndvi_smooth_mean_28,ndvi_smooth_mean_29,ndvi_smooth_mean_30,ndvi_smooth_mean_31,ndvi_smooth_mean_32,ndvi_smooth_mean_33,ndvi_smooth_mean_34,ndvi_smooth_mean_35,ndvi_smooth_mean_36,ndvi_smooth_mean_37,ndvi_smooth_mean_38,ndvi_smooth_mean_39,ndvi_smooth_mean_40,ndvi_smooth_mean_41,ndvi_smooth_mean_42,ndvi_smooth_mean_43,ndvi_smooth_mean_44,ndvi_smooth_mean_45,ndvi_smooth_slope_1,ndvi_smooth_slope_2,ndvi_smooth_slope_3,ndvi_smooth_slope_4,ndvi_smooth_slope_5,ndvi_smooth_slope_6,ndvi_smooth_slope_7,ndvi_smooth_slope_8,ndvi_smooth_slope_9,ndvi_smooth_slope_10,ndvi_smooth_slope_11,ndvi_smooth_slope_12,ndvi_smooth_slope_13,ndvi_smooth_slope_14,ndvi_smooth_slope_15,ndvi_smooth_slope_16,ndvi_smooth_slope_17,ndvi_smooth_slope_18,ndvi_smooth_slope_19,ndvi_smooth_slope_20,ndvi_smooth_slope_21,ndvi_smooth_slope_22,ndvi_smooth_slope_23,ndvi_smooth_slope_24,ndvi_smooth_slope_25,ndvi_smooth_slope_26,ndvi_smooth_slope_27,ndvi_smooth_slope_28,ndvi_smooth_slope_29,ndvi_smooth_slope_30,ndvi_smooth_slope_31,ndvi_smooth_slope_32,ndvi_smooth_slope_33,ndvi_smooth_slope_34,ndvi_smooth_slope_35,ndvi_smooth_slope_36,ndvi_smooth_slope_37,ndvi_smooth_slope_38,ndvi_smooth_slope_39,ndvi_smooth_slope_40,ndvi_smooth_slope_41,ndvi_smooth_slope_42,ndvi_smooth_slope_43,ndvi_smooth_slope_44,ndvi_smooth_slope_45,ndvi_smooth_slope_46,ndvi_smooth_slope_47,ndvi_smooth_slope_48,ndvi_smooth_slope_49,ndvi_smooth_slope_50,ndvi_smooth_slope_51,ndvi_smooth_slope_52,ndvi_smooth_std_1,ndvi_smooth_std_2,ndvi_smooth_std_3,ndvi_smooth_std_4,ndvi_smooth_std_5,ndvi_smooth_std_6,ndvi_smooth_std_7,ndvi_smooth_std_8,ndvi_smooth_std_9,ndvi_smooth_std_10,ndvi_smooth_std_11,ndvi_smooth_std_12,ndvi_smooth_std_13,ndvi_smooth_std_14,ndvi_smooth_std_15,ndvi_smooth_std_16,ndvi_smooth_std_17,ndvi_smooth_std_18,ndvi_smooth_std_19,ndvi_smooth_std_20,ndvi_smooth_std_21,ndvi_smooth_std_22,ndvi_smooth_std_23,ndvi_smooth_std_24,ndvi_smooth_std_25,ndvi_smooth_std_26,ndvi_smooth_std_27,ndvi_smooth_std_28,ndvi_smooth_std_29,ndvi_smooth_std_30,ndvi_smooth_std_31,ndvi_smooth_std_32,ndvi_smooth_std_33,ndvi_smooth_std_34,ndvi_smooth_std_35,ndvi_smooth_std_36,ndvi_smooth_std_37,ndvi_smooth_std_38,ndvi_smooth_std_39,ndvi_smooth_std_40,ndvi_smooth_std_41,ndvi_smooth_std_42,ndvi_smooth_std_43,ndvi_smooth_std_44,ndvi_smooth_std_45,ndvi_smooth_std_46,ndvi_smooth_std_47,ndvi_smooth_std_48,ndvi_smooth_std_49,ndvi_smooth_std_50,ndvi_smooth_std_51,ndvi_smooth_std_52,ndvi_cov,ndvi_mean,ndvi_std,ndvi_mean_norm,ndvi_std_norm,ndvi_cov_norm,health,ndvi_anomaly_36,ndvi_anomaly_37,ndvi_anomaly_38,ndvi_anomaly_39,ndvi_anomaly_40,ndvi_anomaly_41,ndvi_anomaly_42,ndvi_anomaly_43,ppt_28,ppt_29,ppt_30,ppt_31,ppt_32,ppt_33,ppt_34,ppt_35,ppt_36,ppt_37,ppt_38,ppt_39,ppt_40,ppt_41,ppt_42,ppt_43,tmax_28,tmax_29,tmax_30,tmax_31,tmax_32,tmax_33,tmax_34,tmax_35,tmax_36,tmax_37,tmax_38,tmax_39,tmax_40,tmax_41,tmax_42,tmax_43,tmin_28,tmin_29,tmin_30,tmin_31,tmin_32,tmin_33,tmin_34,tmin_35,tmin_36,tmin_37,tmin_38,tmin_39,tmin_40,tmin_41,tmin_42,tmin_43,tmean_28,tmean_29,tmean_30,tmean_31,tmean_32,tmean_33,tmean_34,tmean_35,tmean_36,tmean_37,tmean_38,tmean_39,tmean_40,tmean_41,tmean_42,tmean_43,vpdmax_28,vpdmax_29,vpdmax_30,vpdmax_31,vpdmax_32,vpdmax_33,vpdmax_34,vpdmax_35,vpdmax_36,vpdmax_37,vpdmax_38,vpdmax_39,vpdmax_40,vpdmax_41,vpdmax_42,vpdmax_43,vpdmin_28,vpdmin_29,vpdmin_30,vpdmin_31,vpdmin_32,vpdmin_33,vpdmin_34,vpdmin_35,vpdmin_36,vpdmin_37,vpdmin_38,vpdmin_39,vpdmin_40,vpdmin_41,vpdmin_42,vpdmin_43,cumulative_gdd_28,cumulative_gdd_29,cumulative_gdd_30,cumulative_gdd_31,cumulative_gdd_32,cumulative_gdd_33,cumulative_gdd_34,cumulative_gdd_35,cumulative_gdd_36,cumulative_gdd_37,cumulative_gdd_38,cumulative_gdd_39,cumulative_gdd_40,cumulative_gdd_41,cumulative_gdd_42,cumulative_gdd_43
0,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,"POLYGON ((-119.78208 45.87245, -119.78215 45.8...",1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2016,0.417441,0.417741,0.415264,0.412015,0.410159,0.410159,0.408649,0.406006,0.403366,0.400812,0.398296,0.395780,0.393264,0.390748,0.388232,0.384497,0.373238,0.356197,0.348879,0.346145,0.345504,0.355702,0.381068,0.413351,0.438675,0.443236,0.440521,0.432348,0.424176,0.416003,0.407830,0.379300,0.366964,0.0,0.000000,0.000000,0.000000,0.000000,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,-0.000078,-0.000464,-0.000464,0.000000,0.000000,-0.000378,-0.000378,-0.000376,-0.000359,-0.000359,-0.000359,-0.000359,-0.000359,-0.000359,-0.001071,-0.001783,-0.001851,-0.000534,-0.000351,0.000406,0.003347,0.003689,0.005842,0.000652,0.000652,-0.001168,-0.001168,-0.001168,-0.001168,-0.001168,-0.008094,0.000948,0.000948,0.000948,0.001134,0.001319,0.001319,-0.005969,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000313,0.001003,0.001003,0.000000,0.000000,0.000816,0.000816,0.000811,0.000776,0.000776,0.000776,0.000776,0.000776,0.000776,0.002445,0.003851,0.004258,0.001196,0.000759,0.000913,0.007293,0.007969,0.012621,0.001408,0.001408,0.002522,0.002522,0.002522,0.002522,0.002522,0.018546,0.002048,0.002048,0.002048,0.002457,0.002850,0.002850,0.019600,0.000000,0.061211,0.399301,0.024442,0.488995,0.928728,0.947038,0.677199,-0.073815,-0.047348,-0.041802,-0.036708,-0.031953,-0.027198,-0.022443,-0.017688,0.0,1.310078,0.000000,0.0,1.365116,0.000000,0.00000,0.0,5.789922,1.385271,0.000000,0.0,6.185271,18.615504,4.020155,21.570543,33.639926,36.139926,38.774818,35.305036,36.529842,36.739916,32.894964,33.339922,32.194952,31.160080,27.194952,29.350000,24.050012,20.305036,17.494970,17.774818,13.105038,13.294958,12.884886,11.474800,12.384886,12.429836,10.639926,7.760072,7.615116,4.370156,5.594962,6.115116,6.460084,0.205030,2.794958,4.550012,21.944242,22.429568,26.234941,21.894516,22.867052,24.830620,21.519602,19.065004,18.032170,17.391863,14.584660,17.102157,14.042137,10.906034,10.615336,10.066391,23.099999,24.934884,34.349613,26.010077,27.969767,29.644962,23.610076,23.644960,19.455039,15.065116,12.200000,15.810078,7.844961,7.444961,5.655039,4.700000,1.881505,1.950429,5.053060,1.712215,0.26549,4.835625,2.866083,0.850186,0.000000,0.0,0.0,1.087746,0.0,0.00000,0.0,0.0,83.609693,87.006976,113.644589,83.261614,90.069361,103.814337,80.637215,63.455025,56.225192,51.743038,32.092622,49.715100,28.294959,10.842245,5.222467,5.369773
1,1,-0.000258,-0.014769,0.013737,-0.001123,-0.016449,0.012478,-0.000258,-0.014769,0.013737,206.874710,208.469513,207.776839,21.910873,23.505676,22.812984,"POLYGON ((-119.78179 45.87245, -119.78167 45.8...",1.594803,381.909845,0.038191,-0.814715,0.579861,-0.990090,-0.140434,-0.982037,0.188687,0.092321,0.092584,-0.090921,0.017469,2016,0.296347,0.297577,0.298474,0.299279,0.299738,0.299738,0.302310,0.306810,0.311161,0.310606,0.307821,0.305036,0.302250,0.299465,0.296680,0.294455,0.295685,0.292334,0.288610,0.287386,0.288470,0.300501,0.326470,0.359988,0.386632,0.391433,0.390449,0.385126,0.379804,0.374481,0.369158,0.347759,0.340051,0.0,0.000000,0.000000,0.000000,0.000000,0.000180,0.000180,0.000180,0.000180,0.000180,0.000180,0.000180,0.000180,0.000161,0.000115,0.000115,0.000000,0.000000,0.000643,0.000643,0.000531,-0.000398,-0.000398,-0.000398,-0.000398,-0.000398,-0.000398,-0.000071,0.000256,-0.000778,-0.000271,-0.000149,0.000737,0.003456,0.003770,0.006147,0.000686,0.000686,-0.000760,-0.000760,-0.000760,-0.000760,-0.000760,-0.006208,0.001082,0.001082,0.001082,0.001137,0.001193,0.001193,-0.006293,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000388,0.000388,0.000388,0.000388,0.000388,0.000388,0.000388,0.000388,0.000350,0.000248,0.000248,0.000000,0.000000,0.001389,0.001389,0.001189,0.000860,0.000860,0.000860,0.000860,0.000860,0.000860,0.000395,0.000553,0.001715,0.000621,0.000321,0.001619,0.007517,0.008143,0.013278,0.001482,0.001482,0.001643,0.001643,0.001643,0.001643,0.001643,0.014302,0.002337,0.002337,0.002337,0.002458,0.002576,0.002576,0.020606,0.000000,0.111972,0.322975,0.036164,0.347718,0.878019,0.870145,0.551299,-0.127177,-0.099390,-0.093605,-0.086780,-0.079175,-0.071570,-0.063965,-0.056360,0.0,1.310078,0.000000,0.0,1.365116,0.000000,0.00000,0.0,5.789922,1.385271,0.000000,0.0,6.185271,18.615504,4.020155,21.570543,33.639926,36.139926,38.774818,35.305036,36.529842,36.739916,32.894964,33.339922,32.194952,31.160080,27.194952,29.350000,24.050012,20.305036,17.494970,17.774818,13.105038,13.294958,12.884886,11.474800,12.384886,12.429836,10.639926,7.760072,7.615116,4.370156,5.594962,6.115116,6.460084,0.205030,2.794958,4.550012,21.944242,22.429568,26.234941,21.894516,22.867052,24.830620,21.519602,19.065004,18.032170,17.391863,14.584660,17.102157,14.042137,10.906034,10.615336,10.066391,23.099999,24.934884,34.349613,26.010077,27.969767,29.644962,23.610076,23.644960,19.455039,15.065116,12.200000,15.810078,7.844961,7.444961,5.655039,4.700000,1.881505,1.950429,5.053060,1.712215,0.26549,4.835625,2.866083,0.850186,0.000000,0.0,0.0,1.087746,0.0,0.00000,0.0,0.0,83.609693,87.006976,113.644589,83.261614,90.069361,103.814337,80.637215,63.455025,56.225192,51.743038,32.092622,49.715100,28.294959,10.842245,5.222467,5.369773
2,2,0.000065,-0.030229,0.034444,-0.000754,-0.043223,0.027175,0.000065,-0.030229,0.034444,205.507690,207.790955,206.759655,20.543854,22.827118,21.795817,"POLYGON ((-119.78139 45.87246, -119.78129 45.8...",2.283264,304.757142,0.030476,-0.711031,0.703161,-0.996336,0.085528,-0.883329,0.468753,0.124799,0.125451,-0.110815,0.058806,2016,0.250561,0.250514,0.250457,0.250396,0.250361,0.250361,0.251416,0.253263,0.255011,0.253482,0.250464,0.247445,0.244427,0.241408,0.238389,0.235753,0.235478,0.233358,0.229710,0.228797,0.229812,0.239585,0.260539,0.288141,0.310150,0.313479,0.312934,0.309484,0.306033,0.302583,0.299132,0.283584,0.279498,0.0,0.000000,0.000000,0.000000,0.000000,-0.000006,-0.000006,-0.000006,-0.000006,-0.000006,-0.000006,-0.000006,-0.000006,-0.000007,-0.000009,-0.000009,0.000000,0.000000,0.000264,0.000264,0.000189,-0.000431,-0.000431,-0.000431,-0.000431,-0.000431,-0.000431,-0.000208,0.000015,-0.000597,-0.000253,-0.000097,0.000609,0.002790,0.003041,0.005146,0.000476,0.000476,-0.000493,-0.000493,-0.000493,-0.000493,-0.000493,-0.004562,0.001114,0.001114,0.001114,0.001081,0.001048,0.001048,-0.004970,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000014,0.000014,0.000014,0.000014,0.000014,0.000014,0.000014,0.000014,0.000015,0.000019,0.000019,0.000000,0.000000,0.000570,0.000570,0.000459,0.000932,0.000932,0.000932,0.000932,0.000932,0.000932,0.000513,0.000033,0.001293,0.000607,0.000210,0.001336,0.006067,0.006570,0.011116,0.001027,0.001027,0.001065,0.001065,0.001065,0.001065,0.001065,0.010584,0.002408,0.002408,0.002408,0.002336,0.002264,0.002264,0.016306,0.000000,0.107003,0.265529,0.028412,0.241385,0.911552,0.877673,0.464659,-0.199024,-0.175872,-0.171559,-0.164295,-0.154818,-0.145341,-0.135863,-0.126386,0.0,1.310078,0.000000,0.0,1.365116,0.000000,0.00000,0.0,5.789922,1.385271,0.000000,0.0,6.185271,18.615504,4.020155,21.570543,33.639926,36.139926,38.774818,35.305036,36.529842,36.739916,32.894964,33.339922,32.194952,31.160080,27.194952,29.350000,24.050012,20.305036,17.494970,17.774818,13.105038,13.294958,12.884886,11.474800,12.384886,12.429836,10.639926,7.760072,7.615116,4.370156,5.594962,6.115116,6.460084,0.205030,2.794958,4.550012,21.944242,22.429568,26.234941,21.894516,22.867052,24.830620,21.519602,19.065004,18.032170,17.391863,14.584660,17.102157,14.042137,10.906034,10.615336,10.066391,23.099999,24.934884,34.349613,26.010077,27.969767,29.644962,23.610076,23.644960,19.455039,15.065116,12.200000,15.810078,7.844961,7.444961,5.655039,4.700000,1.881505,1.950429,5.053060,1.712215,0.26549,4.835625,2.866083,0.850186,0.000000,0.0,0.0,1.087746,0.0,0.00000,0.0,0.0,83.609693,87.006976,113.644589,83.261614,90.069361,103.814337,80.637215,63.455025,56.225192,51.743038,32.092622,49.715100,28.294959,10.842245,5.222467,5.369773
3,3,0.000241,-0.022650,0.018867,0.000610,-0.020701,0.012653,0.000241,-0.022650,0.018867,210.499161,214.308624,212.434447,25.535324,29.344788,27.470613,"POLYGON ((-119.78299 45.87287, -119.78300 45.8...",3.809464,416.261511,0.041626,-0.937885,0.346945,-0.987084,-0.160203,-0.996496,0.083636,0.160190,0.161575,-0.161008,0.013513,2016,0.254788,0.256395,0.257737,0.259006,0.259415,0.258677,0.259358,0.261101,0.262795,0.262841,0.262139,0.261436,0.260734,0.260031,0.259329,0.258572,0.257482,0.253426,0.249988,0.248291,0.246853,0.252256,0.272063,0.299197,0.321835,0.326229,0.325800,0.321753,0.317706,0.313659,0.309612,0.297303,0.296758,0.0,0.000000,0.000000,0.000000,0.000000,0.000233,0.000233,0.000233,0.000233,0.000233,0.000233,0.000233,0.000233,0.000218,0.000181,0.000181,-0.000105,-0.000105,0.000249,0.000249,0.000212,-0.000100,-0.000100,-0.000100,-0.000100,-0.000100,-0.000100,-0.000132,-0.000163,-0.000682,-0.000307,-0.000225,-0.000168,0.002565,0.002892,0.005189,0.000628,0.000628,-0.000578,-0.000578,-0.000578,-0.000578,-0.000578,-0.003257,0.001269,0.001269,0.001269,0.001453,0.001636,0.001636,-0.004656,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000503,0.000503,0.000503,0.000503,0.000503,0.000503,0.000503,0.000503,0.000472,0.000392,0.000392,0.000228,0.000228,0.000538,0.000538,0.000469,0.000217,0.000217,0.000217,0.000217,0.000217,0.000217,0.000287,0.000353,0.001501,0.000679,0.000485,0.000364,0.005615,0.006247,0.011209,0.001356,0.001356,0.001249,0.001249,0.001249,0.001249,0.001249,0.007662,0.002742,0.002742,0.002742,0.003144,0.003534,0.003534,0.015480,0.000000,0.114910,0.277609,0.031900,0.263746,0.896465,0.865696,0.482023,-0.187968,-0.164187,-0.158809,-0.151429,-0.142548,-0.133668,-0.124787,-0.115906,0.0,1.310078,0.000000,0.0,1.365116,0.000000,0.00000,0.0,5.789922,1.385271,0.000000,0.0,6.185271,18.615504,4.020155,21.570543,33.639926,36.139926,38.774818,35.305036,36.529842,36.739916,32.894964,33.339922,32.194952,31.160080,27.194952,29.350000,24.050012,20.305036,17.494970,17.774818,13.105038,13.294958,12.884886,11.474800,12.384886,12.429836,10.639926,7.760072,7.615116,4.370156,5.594962,6.115116,6.460084,0.205030,2.794958,4.550012,21.944242,22.429568,26.234941,21.894516,22.867052,24.830620,21.519602,19.065004,18.032170,17.391863,14.584660,17.102157,14.042137,10.906034,10.615336,10.066391,23.099999,24.934884,34.349613,26.010077,27.969767,29.644962,23.610076,23.644960,19.455039,15.065116,12.200000,15.810078,7.844961,7.444961,5.655039,4.700000,1.881505,1.950429,5.053060,1.712215,0.26549,4.835625,2.866083,0.850186,0.000000,0.0,0.0,1.087746,0.0,0.00000,0.0,0.0,83.609693,87.006976,113.644589,83.261614,90.069361,103.814337,80.637215,63.455025,56.225192,51.743038,32.092622,49.715100,28.294959,10.842245,5.222467,5.369773
4,4,0.000753,-0.013419,0.014943,0.000611,-0.011132,0.012551,0.000753,-0.013419,0.014943,209.319901,213.504730,211.261849,24.356064,28.540894,26.298020,"POLYGON ((-119.78263 45.87269, -119.78269 45.8...",4.184830,934.859055,0.093486,-0.913900,0.405938,-0.986932,-0.161140,-0.993317,0.115418,0.115925,0.116447,-0.115669,0.013440,2016,0.410375,0.410378,0.410417,0.410467,0.411159,0.412710,0.413384,0.413401,0.413404,0.412963,0.412320,0.411677,0.411034,0.410391,0.409748,0.408725,0.405354,0.407031,0.403591,0.397513,0.392331,0.396174,0.414907,0.440816,0.462198,0.465584,0.461746,0.452489,0.443232,0.433975,0.424719,0.392644,0.376749,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000002,0.000007,0.000007,0.000222,0.000222,0.000002,0.000002,-0.000008,-0.000092,-0.000092,-0.000092,-0.000092,-0.000092,-0.000092,-0.000314,-0.000536,0.000057,-0.000793,-0.000889,-0.000455,0.002403,0.002740,0.004983,0.000484,0.000484,-0.001322,-0.001322,-0.001322,-0.001322,-0.001322,-0.009136,0.000673,0.000673,0.000673,0.000822,0.000972,0.000972,-0.005717,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000006,0.000015,0.000015,0.000479,0.000479,0.000005,0.000005,0.000033,0.000198,0.000198,0.000198,0.000198,0.000198,0.000198,0.000722,0.001158,0.001051,0.001721,0.001920,0.000994,0.005276,0.005920,0.010764,0.001045,0.001045,0.002857,0.002857,0.002857,0.002857,0.002857,0.020853,0.001453,0.001453,0.001453,0.001785,0.002100,0.002100,0.018684,0.000000,0.047379,0.412649,0.019551,0.513702,0.949885,0.967991,0.701845,-0.046349,-0.023825,-0.019454,-0.015483,-0.011812,-0.008141,-0.004471,-0.000800,0.0,1.310078,0.000000,0.0,1.365116,0.000000,0.00000,0.0,5.789922,1.385271,0.000000,0.0,6.185271,18.615504,4.020155,21.570543,33.639926,36.139926,38.774818,35.305036,36.529842,36.739916,32.894964,33.339922,32.194952,31.160080,27.194952,29.350000,24.050012,20.305036,17.494970,17.774818,13.105038,13.294958,12.884886,11.474800,12.384886,12.429836,10.639926,7.760072,7.615116,4.370156,5.594962,6.115116,6.460084,0.205030,2.794958,4.550012,21.944242,22.429568,26.234941,21.894516,22.867052,24.830620,21.519602,19.065004,18.032170,17.391863,14.584660,17.102157,14.042137,10.906034,10.615336,10.066391,23.099999,24.934884,34.349613,26.010077,27.969767,29.644962,23.610076,23.644960,19.455039,15.065116,12.200000,15.810078,7.844961,7.444961,5.655039,4.700000,1.881505,1.950429,5.053060,1.712215,0.26549,4.835625,2.866083,0.850186,0.000000,0.0,0.0,1.087746,0.0,0.00000,0.0,0.0,83.609693,87.006976,113.644589,83.261614,90.069361,103.814337,80.637215,63.455025,56.225192,51.743038,32.092622,49.715100,28.294959,10.842245,5.222467,5.369773
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [21]:
# # Optional: could also add slope magnitude transforms
# df['slope_squared'] = df['slope_mean'] ** 2
# df['slope_log'] = np.log1p(df['slope_mean'])  # log(1 + slope)

for i in range(28, 44, 1):
    
    df[f'water_availability_{i}'] = df[f'ppt_{i}'] / (1 +  df[f'cumulative_gdd_{i}'])
    df[f'diurnal_temp_range_{i}'] = df[f'tmax_{i}'] / df[f'tmin_{i}']
    df[f'stress_index{i}'] = df[f'vpdmax_{i}'] / (df[f'ppt_{i}'] + 0.1)
df['local_relief'] = df['elev_mean'] - df['elev_min']

df['total_relief_log'] = np.log1p(df['total_relief'])

In [22]:
soil = pd.read_pickle('../data/soil/plot_summary.pkl')

In [23]:
df = pd.merge(df, soil, how = 'inner', on = 'plot_id')

In [24]:
df = pd.DataFrame(df.drop(columns = 'geometry'))

In [25]:
df

,plot_id,curve_mean,curve_min,curve_max,pro_curve_mean,pro_curve_min,pro_curve_max,plan_curve_mean,plan_curve_min,plan_curve_max,elev_min,elev_max,elev_mean,elev_dev_min,elev_dev_max,elev_dev_mean,total_relief,area_m2,area_ha,aspect_min_cos,aspect_min_sin,aspect_max_cos,aspect_max_sin,aspect_mean_cos,aspect_mean_sin,slope_rad,slope_grad,slope_x,slope_y,year,ndvi_smooth_mean_13,ndvi_smooth_mean_14,ndvi_smooth_mean_15,ndvi_smooth_mean_16,ndvi_smooth_mean_17,ndvi_smooth_mean_18,ndvi_smooth_mean_19,ndvi_smooth_mean_20,ndvi_smooth_mean_21,ndvi_smooth_mean_22,ndvi_smooth_mean_23,ndvi_smooth_mean_24,ndvi_smooth_mean_25,ndvi_smooth_mean_26,ndvi_smooth_mean_27,ndvi_smooth_mean_28,ndvi_smooth_mean_29,ndvi_smooth_mean_30,ndvi_smooth_mean_31,ndvi_smooth_mean_32,ndvi_smooth_mean_33,ndvi_smooth_mean_34,ndvi_smooth_mean_35,ndvi_smooth_mean_36,ndvi_smooth_mean_37,ndvi_smooth_mean_38,ndvi_smooth_mean_39,ndvi_smooth_mean_40,ndvi_smooth_mean_41,ndvi_smooth_mean_42,ndvi_smooth_mean_43,ndvi_smooth_mean_44,ndvi_smooth_mean_45,ndvi_smooth_slope_1,ndvi_smooth_slope_2,ndvi_smooth_slope_3,ndvi_smooth_slope_4,ndvi_smooth_slope_5,ndvi_smooth_slope_6,ndvi_smooth_slope_7,ndvi_smooth_slope_8,ndvi_smooth_slope_9,ndvi_smooth_slope_10,ndvi_smooth_slope_11,ndvi_smooth_slope_12,ndvi_smooth_slope_13,ndvi_smooth_slope_14,ndvi_smooth_slope_15,ndvi_smooth_slope_16,ndvi_smooth_slope_17,ndvi_smooth_slope_18,ndvi_smooth_slope_19,ndvi_smooth_slope_20,ndvi_smooth_slope_21,ndvi_smooth_slope_22,ndvi_smooth_slope_23,ndvi_smooth_slope_24,ndvi_smooth_slope_25,ndvi_smooth_slope_26,ndvi_smooth_slope_27,ndvi_smooth_slope_28,ndvi_smooth_slope_29,ndvi_smooth_slope_30,ndvi_smooth_slope_31,ndvi_smooth_slope_32,ndvi_smooth_slope_33,ndvi_smooth_slope_34,ndvi_smooth_slope_35,ndvi_smooth_slope_36,ndvi_smooth_slope_37,ndvi_smooth_slope_38,ndvi_smooth_slope_39,ndvi_smooth_slope_40,ndvi_smooth_slope_41,ndvi_smooth_slope_42,ndvi_smooth_slope_43,ndvi_smooth_slope_44,ndvi_smooth_slope_45,ndvi_smooth_slope_46,ndvi_smooth_slope_47,ndvi_smooth_slope_48,ndvi_smooth_slope_49,ndvi_smooth_slope_50,ndvi_smooth_slope_51,ndvi_smooth_slope_52,ndvi_smooth_std_1,ndvi_smooth_std_2,ndvi_smooth_std_3,ndvi_smooth_std_4,ndvi_smooth_std_5,ndvi_smooth_std_6,ndvi_smooth_std_7,ndvi_smooth_std_8,ndvi_smooth_std_9,ndvi_smooth_std_10,ndvi_smooth_std_11,ndvi_smooth_std_12,ndvi_smooth_std_13,ndvi_smooth_std_14,ndvi_smooth_std_15,ndvi_smooth_std_16,ndvi_smooth_std_17,ndvi_smooth_std_18,ndvi_smooth_std_19,ndvi_smooth_std_20,ndvi_smooth_std_21,ndvi_smooth_std_22,ndvi_smooth_std_23,ndvi_smooth_std_24,ndvi_smooth_std_25,ndvi_smooth_std_26,ndvi_smooth_std_27,ndvi_smooth_std_28,ndvi_smooth_std_29,ndvi_smooth_std_30,ndvi_smooth_std_31,ndvi_smooth_std_32,ndvi_smooth_std_33,ndvi_smooth_std_34,ndvi_smooth_std_35,ndvi_smooth_std_36,ndvi_smooth_std_37,ndvi_smooth_std_38,ndvi_smooth_std_39,ndvi_smooth_std_40,ndvi_smooth_std_41,ndvi_smooth_std_42,ndvi_smooth_std_43,ndvi_smooth_std_44,ndvi_smooth_std_45,ndvi_smooth_std_46,ndvi_smooth_std_47,ndvi_smooth_std_48,ndvi_smooth_std_49,ndvi_smooth_std_50,ndvi_smooth_std_51,ndvi_smooth_std_52,ndvi_cov,ndvi_mean,ndvi_std,ndvi_mean_norm,ndvi_std_norm,ndvi_cov_norm,health,ndvi_anomaly_36,ndvi_anomaly_37,ndvi_anomaly_38,ndvi_anomaly_39,ndvi_anomaly_40,ndvi_anomaly_41,ndvi_anomaly_42,ndvi_anomaly_43,ppt_28,ppt_29,ppt_30,ppt_31,ppt_32,ppt_33,ppt_34,ppt_35,ppt_36,ppt_37,ppt_38,ppt_39,ppt_40,ppt_41,ppt_42,ppt_43,tmax_28,tmax_29,tmax_30,tmax_31,tmax_32,tmax_33,tmax_34,tmax_35,tmax_36,tmax_37,tmax_38,tmax_39,tmax_40,tmax_41,tmax_42,tmax_43,tmin_28,tmin_29,tmin_30,tmin_31,tmin_32,tmin_33,tmin_34,tmin_35,tmin_36,tmin_37,tmin_38,tmin_39,tmin_40,tmin_41,tmin_42,tmin_43,tmean_28,tmean_29,tmean_30,tmean_31,tmean_32,tmean_33,tmean_34,tmean_35,tmean_36,tmean_37,tmean_38,tmean_39,tmean_40,tmean_41,tmean_42,tmean_43,vpdmax_28,vpdmax_29,vpdmax_30,vpdmax_31,vpdmax_32,vpdmax_33,vpdmax_34,vpdmax_35,vpdmax_36,vpdmax_37,vpdmax_38,vpdmax_39,vpdmax_40,vpdmax_41,vpdmax_42,vpdmax_43,vpdmin_28,vpdmin_29,vpdmin_30,vpdmin_31,vpdmin_32,vpdmin_33,vpdmin_34,vpdmin_35,vpdmin_36,vpdmin_37,vpdmin_38,vpdmin_39,vpdmin_40,vpdmin_41,vpdmin_42,vpdmin_43,cumulative_gdd_28,cumulative_gdd_29,cumulative_gdd_30,cumulative_gdd_31,cumulative_gdd_32,cumulative_gdd_33,cumulative_gdd_34,cumulative_gdd_35,cumulative_gdd_36,cumulative_gdd_37,cumulative_gdd_38,cumulative_gdd_39,cumulative_gdd_40,cumulative_gdd_41,cumulative_gdd_42,cumulative_gdd_43,water_availability_28,diurnal_temp_range_28,stress_index28,water_availability_29,diurnal_temp_range_29,stress_index29,water_availability_30,diurnal_temp_range_30,stress_index30,water_availability_31,diurnal_temp_range_31,stress_index31,water_availability_32,diurnal_temp_range_32,stress_index32,water_availability_33,diurnal_temp_range_33,stress_index33,water_availability_34,diurnal_temp_range_34,stress_index34,water_availability_35,diurnal_temp_range_35,stress_index35,water_availability_36,diurnal_temp_range_36,stress_index36,water_availability_37,diurnal_temp_range_37,stress_index37,water_availability_38,diurnal_temp_range_38,stress_index38,water_availability_39,diurnal_temp_range_39,stress_index39,water_availability_40,diurnal_temp_range_40,stress_index40,water_availability_41,diurnal_temp_range_41,stress_index41,water_availability_42,diurnal_temp_range_42,stress_index42,water_availability_43,diurnal_temp_range_43,stress_index43,local_relief,total_relief_log,sandtotal_r,silttotal_r,claytotal_r,ph1to1h2o_r,cec7_r,om_r,awc_r,ec_r,dbovendry_r,kffact,kwfact,caco3_r,frag3to10_r,fraggt10_r,wthirdbar_r,wtenthbar_r,wfifteenbar_r,wsatiated_r,profile_depth,max_depth,drain_ord,restrictiondepth_cm,dominant_mukey
0,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2016,0.417441,0.417741,0.415264,0.412015,0.410159,0.410159,0.408649,0.406006,0.403366,0.400812,0.398296,0.395780,0.393264,0.390748,0.388232,0.384497,0.373238,0.356197,0.348879,0.346145,0.345504,0.355702,0.381068,0.413351,0.438675,0.443236,0.440521,0.432348,0.424176,0.416003,0.407830,0.379300,0.366964,0.0,0.000000,0.000000,0.000000,0.000000,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,0.000076,-0.000078,-0.000464,-0.000464,0.000000,0.000000,-0.000378,-0.000378,-0.000376,-0.000359,-0.000359,-0.000359,-0.000359,-0.000359,-0.000359,-0.001071,-0.001783,-0.001851,-0.000534,-0.000351,0.000406,0.003347,0.003689,0.005842,0.000652,0.000652,-0.001168,-0.001168,-0.001168,-0.001168,-0.001168,-0.008094,0.000948,0.000948,0.000948,0.001134,0.001319,0.001319,-0.005969,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000164,0.000313,0.001003,0.001003,0.000000,0.000000,0.000816,0.000816,0.000811,0.000776,0.000776,0.000776,0.000776,0.000776,0.000776,0.002445,0.003851,0.004258,0.001196,0.000759,0.000913,0.007293,0.007969,0.012621,0.001408,0.001408,0.002522,0.002522,0.002522,0.002522,0.002522,0.018546,0.002048,0.002048,0.002048,0.002457,0.002850,0.002850,0.019600,0.000000,0.061211,0.399301,0.024442,0.488995,0.928728,0.947038,0.677199,-0.073815,-0.047348,-0.041802,-0.036708,-0.031953,-0.027198,-0.022443,-0.017688,0.000000,1.310078,0.000000,0.0,1.365116,0.000000,0.000000,0.00000,5.789922,1.385271,0.000000,0.000000,6.185271,18.615504,4.020155,21.570543,33.639926,36.139926,38.774818,35.305036,36.529842,36.739916,32.894964,33.339922,32.194952,31.160080,27.194952,29.350000,24.050012,20.305036,17.494970,17.774818,13.105038,13.294958,12.884886,11.474800,12.384886,12.429836,10.639926,7.760072,7.615116,4.370156,5.594962,6.115116,6.460084,0.205030,2.794958,4.550012,21.944242,22.429568,26.234941,21.894516,22.867052,24.830620,21.519602,19.065004,18.032170,17.391863,14.584660,17.102157,14.042137,10.906034,10.615336,10.066391,23.099999,24.934884,34.349613,26.010077,27.969767,29.644962,23.610076,23.644960,19.455039,15.065116,12.200000,15.810078,7.844961,7.444961,5.655039,4.700000,1.881505,1.950429,5.053060,1.712215,0.265490,4.835625,2.866083,0.850186,0.000000,0.000000,0.000000,1.087746,0.000000,0.000000,0.0,0.0,83.609693,87.006976,113.644589,83.261614,90.069361,103.814337,80.637215,63.455025,56.225192,51.743038,32.092622,49.715100,28.294959,10.842245,5.222467,5.369773,0.000000,2.566946,230.999994,0.014886,2.718318,17.683342,0.000000,3.009326,343.496130,0.0,3.076745,260.100766,0.014990,2.949550,19.090476,0.000000,2.955784,296.449616,0.000000,3.091653,236.100765,0.000000,4.296342,236.449601,0.101178,4.227769,3.303106,0.026265,7.130198,10.143006,0.000000,4.860614,122.000003,0.000000,4.799582,158.100779,0.211138,3.722864,1.248150,1.571957,99.034506,0.397796,0.646071,6.259475,1.372531,3.386391,3.906543,0.216884,0.696013,0.926511,81.037500,16.462500,2.500000,7.0,3.500000,0.328125,0.071719,0.000000,1.552031,0.282656,0.210469,0.000000,2.625,0.984375,7.171875,11.750000,1.514063,29.875000,106.117647,106.117647,1.0,37.647059,69511
1,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2017,0.329644,0.330595,0.331926,0.333256,0.334587,0.338387,0.351077,0.364508,0.376660,0.385999,0.395252,0.404505,0.399311,0.355272,0.339719,0.331969,0.322669,0.320248,0.318124,0.322323,0.324225,0.321754,0.322187,0.327781,0.330168,0.331366,0.333434,0.339194,0.339164,0.338132,0.337109,0.336203,0.335328,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000014,0.000190,0.000190,0.000190,0.000190,0.001425,0.001919,0.001919,0.001386,0.001322,0.001322,0.001322,-0.003970,-0.004277,-0.000937,-0.001231,-0.000664,-0.000828,0.000356,0.000338,0.000090,-0.000614,0.001560,0.000333,0.000323,0.000109,0.000761,0.000437,-0.000147,-0.000147,-0.000141,-0.000125,-0.000125,-0.000125,-0.000275,-0.000650,-0.000046,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000190,0.000411,0.000411,0.000411,0.000411,0.003191,0.004145,0.004145,0.002999,0.002856,0.002856,0.002856,0.008904,0.009495,0.002024,0.002659,0.002196,0.001798,0.001029,0.000758,0.000448,0.001365,0.003402,0.000719,0.000713,0.000236,0.001703,0.001147,0.000319,0.000319,0.000305,0.000270,0.000270,0.000270,0.000647,0.001404,0.000650,0.000000,0.000000,0.000000,0.066718,0.341236,0.022767,0.381518,0.935975,0.938697,0.598005,-0.142266,-0.128436,-0.106456,-0.089132,-0.076720,-0.069060,-0.062112,-0.055108,0.000000,0.000000,0.000000,0.0,1.955039,0.000000,0.000000,0.00000,0.000000,0.644961,3.500000,0.165116,0.000000,1.220155,23.010078,0.000000,34.539920,37.739916,36.450006,38.194952,38.850000,33.994970,34.149988,36.694952,32.460084,33.705030,22.905042,28.394964,23.694952,17.784880,21.394964,20.294958,11.729854,11.294958,14.050012,14.950006,12.950006,10.539920,9.739916,13.560074,11.215122,5.860078,3.515110,8.394964,2.305036,-0.815110,0.015110,1.994970,23.469933,23.499556,25.381009,26.465334,26.314228,21.716722,21.802823,24.371096,22.391474,17.965728,13.128242,16.541088,12.202159,8.616778,11.253931,10.224969,25.044961,28.244961,29.900000,32.355039,33.810078,23.044961,26.310078,30.200000,23.975194,23.320154,9.610078,14.355039,12.800000,7.955039,9.120155,6.044961,1.874487,3.739983,5.032998,6.032692,0.000000,2.920158,0.000000,4.213529,0.000000,2.647971,0.000000,0.157001,0.367370,0.000000,0.0,0.0,94.289530,94.496891,107.667065,115.257339,114.199593,82.017053,82.619761,100.597675,86.740318,55.760098,21.897693,45.787616,15.415114,0.932563,9.050005,3.857346,0.000000,2.944616,250.449612,0.000000,3.341306,282.449605,0.000000,2.594304,299.000001,0.0,2.554845,323.550389,0.016971,2.999999,16.452282,0.000000,3.225354,230.449607,0.000000,3.506189,263.100776,0.000000,2.706103,301.999998,0.000000,2.894314,239.751937,0.011363,5.751635,31.303849,0.152854,6.516167,2.669466,0.003529,3.382381,54.146198,0.000000,10.279645,127.999997,0.631366,-21.819005,6.025837,2.289559,1415.988508,0.394640,0.000000,10.173064,60.449614,0.696013,0.926511,81.037500,16.462500,2.500000,7.0,3.500000,0.328125,0.071719,0.000000,1.552031,0.282656,0.210469,0.000000,2.625,0.984375,7.171875,11.750000,1.514063,29.875000,106.117647,106.117647,1.0,37.647059,69511
2,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2018,0.337342,0.339505,0.341668,0.343619,0.344173,0.345555,0.346938,0.343668,0.341470,0.332540,0.330672,0.330827,0.320533,0.319656,0.314177,0.313716,0.306276,0.305823,0.303524,0.306111,0.314969,0.329831,0.339823,0.344996,0.351547,0.354465,0.366220,0.378805,0.389178,0.428417,0.467546,0.480323,0.492458,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000671,0.001297,0.000309,0.000309,0.000309,0.000309,0.000167,0.000197,0.000197,0.000197,-0.000371,-0.000499,-0.001485,0.000213,-0.000566,-0.000727,-0.000688,-0.000402,-0.000188,-0.001330,-0.000526,0.000361,0.000039,0.002017,0.002040,0.000333,0.001936,0.000417,0.000417,0.003317,0.001256,0.002308,0.008811,0.001145,0.003129,0.001009,0.001136,-0.003627,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.001467,0.002802,0.000668,0.000668,0.000668,0.000668,0.000435,0.000427,0.000427,0.000427,0.000943,0.001097,0.003556,0.000460,0.001499,0.002002,0.001735,0.000936,0.000503,0.003396,0.001362,0.001030,0.000733,0.004407,0.004407,0.000907,0.004447,0.000901,0.000901,0.007535,0.002714,0.005300,0.019070,0.002474,0.006792,0.002209,0.002454,0.010856,0.000000,0.000000,0.000000,0.000000,0.000000,0.153744,0.355367,0.054636,0.407674,0.798117,0.806869,0.571971,-0.119758,-0.111295,-0.106242,-0.089821,-0.072075,-0.056171,0.018308,0.098746,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.555039,0.00000,0.000000,0.000000,0.000000,0.000000,8.930232,9.785271,0.000000,1.410078,38.839922,38.284880,38.360078,39.005048,39.294958,36.484878,32.894964,32.894964,33.415120,25.249994,25.094962,27.794958,23.484878,21.484878,18.994970,19.615116,13.094962,11.950006,12.715122,12.229854,12.474800,12.139926,10.384886,9.360078,10.094962,6.460084,5.505048,4.450006,3.249994,0.705030,0.160080,2.105038,24.413899,24.148504,26.583888,24.722038,25.505977,23.633835,20.749946,19.454266,20.178242,16.018936,14.948948,15.640699,11.288924,10.804261,9.663566,12.058583,32.844961,34.579845,32.920155,34.775194,35.189922,30.114729,22.744961,21.355040,22.575194,12.275194,13.410078,17.655039,11.655038,8.944961,8.400000,6.555039,2.517418,4.326097,6.058558,0.639583,2.014639,3.275336,1.746291,0.000000,2.203734,0.000000,0.050233,0.521719,0.000000,0.000000,0.0,0.0,100.897294,99.039528,116.087214,103.054268,108.541839,95.436842,75.249619,66.179861,71.247694,42.132552,34.642637,39.484894,10.655033,6.839914,0.650003,14.760087,0.000000,2.966020,328.449609,0.000000,3.203754,345.798454,0.000000,3.016886,329.201546,0.0,3.189331,347.751940,0.000000,3.149947,351.899223,0.000000,3.005362,301.147286,0.007279,3.167581,34.723076,0.000000,3.514390,213.550399,0.000000,3.310079,225.751937,0.000000,3.908617,122.751940,0.000000,4.558536,134.100778,0.000000,6.246049,176.550386,0.766213,7.226130,1.290669,1.248135,30.473712,0.904878,0.000000,118.659494,83.999997,0.089471,9.318179,4.340862,0.696013,0.926511,81.037500,16.462500,2.500000,7.0,3.500000,0.328125,0.071719,0.000000,1.552031,0.282656,0.210469,0.000000,2.625,0.984375,7.171875,11.750000,1.514063,29.875000,106.117647,106.117647,1.0,37.647059,69511
3,0,0.000489,-0.009361,0.013225,0.000620,-0.010633,0.013191,0.000489,-0.009361,0.013225,207.326294,208.851974,208.022307,22.362457,23.888138,23.058465,1.525681,451.141838,0.045114,-0.909044,0.416701,-0.983593,-0.180402,-0.996750,0.080559,0.087617,0.087841,-0.087556,0.007076,2019,0.420147,0.417991,0.417286,0.416581,0.415876,0.414144,0.390046,0.377250,0.367943,0.333504,0.307616,0.298621,0.277066,0.268343,0.257594,0.253854,0.250562,0.249726,0.247150,0.253554,0.258864,0.258951,0.259078,0.258787,0.258504,0.259266,0.260198,0.260873,0.258438,0.255991,0.253653,0.256494,0.299480,0.0,-0.000042,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000232,-0.000569,-0.000935,-0.000584,-0.000101,-0.000101,-0.000101,-0.000101,-0.001171,-0.003517,-0.001153,-0.002081,-0.003267,-0.001364,-0.002576,-0.002017,-0.002022,-0.001092,-0.000099,-0.000736,0.000314,0.000672,0.000888,0.000297,0.000071,0.000183,-0.000065,0.000034,0.000133,0.000133,-0.000015,-0.000440,-0.000320,-0.000360,0.004201,0.004435,0.002910,0.002761,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000300,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.000502,0.003862,0.002245,0.001262,0.000218,0.000218,0.000218,0.000218,0.003792,0.007767,0.002490,0.005189,0.007391,0.003863,0.005726,0.005762,0.004371,0.002362,0.000237,0.001595,0.001161,0.001979,0.001919,0.001101,0.000213,0.000487,0.000139,0.000133,0.000287,0.000287,0.000209,0.000959,0.000692,0.000778,0.010231,0.009920,0.006288,0.005965,0.000000,0.000000,0.000000,0.000000,0.000000,0.239423,0.338190,0.080971,0.375880,0.684197,0.677082,0.505802,-0.178223,-0.171176,-0.164196,-0.157226,-0.140817,-0.106719,-0.090181,-0.070564,0.000000,0.275194,1.410077,0.0,4.934884,0.000000,1.865116,0.00000,0.000000,3.134884,3.860465,0.220155,0.000000,0.000000,8.140310,0.000000,32.749994,32.694952,36.294958,35.639926,38.749994,32.594962,34.439928,34.494970,32.450006,28.660080,25.550012,26.850000,21.039920,24.394964,17.794958,22.205030,13.039920,10.405042,10.905042,12.484878,14.284880,12.739916,11.929836,11.284880,12.950006,9.950006,9.994970,3.850000,-0.394962,-3.294970,2.105038,-2.705042,23.203876,21.364951,23.107088,23.998835,24.574583,22.781341,22.389922,23.492469,22.706091,19.053934,16.770708,13.956422,10.554982,8.180011,10.715007,10.228627,19.820155,23.199999,29.300001,24.810078,31.910078,21.644962,23.434883,25.055039,20.275194,14.020155,9.910078,10.855039,9.955039,11.300000,6.744961,8.555039,2.356615,1.404485,2.935186,1.409238,0.000000,1.507120,0.000000,1.690513,1.845356,0.000000,0.000000,0.000000,0.545450,0.076900,0.0,0.0,92.427133,79.554654,91.749617,97.991846,102.022084,89.469386,86.729455,94.447280,88.942635,63.377537,47.394958,31.512397,9.944949,5.132562,6.907365,9.197660,0.000000,2.511518,198.201552,0.003416,3.142222,61.834709,0.015203,3.328273,19.402978,0.0,2.854648,248.100777,0.047901,2.712658,6.337798,0.000000,2.558491,216.449621,0.021260,2.886874,11.925443,0.000000,3.056742,250.550387,0.000000,2.505791,202.751935,0.048695,2.880408,4.334052,0.079770,2.556287,2.502251,0.006771,6.974026,33.905570,0.000000,-53.270682,99.550388,0.000000,-7.403698,113.000000,1.029459,8.453511,0.818532,0.000000,-8.208756,85.550389,0.696013,0.926511,81.037500,16.462500,2.500000,7.0,3.500000,0.328125,0.071719,0.000000,1.552031,0.282656,0.210469,0.000000,2.625,0.984375,7.171875,11.750000,1.514063,29.875000,106.117647,106.117647,1.0,37.647059,69511

In [26]:
df.to_pickle('../data/df.pkl')