# 00 — RSU Assembly

Load all 12 pilot RSU JSON files. Each RSU contains 4-5 native staple foods covering macronutrient categories:
**carb | fat | protein | aromatic | fermented**

Metabolite profiles are per food, not per RSU.

**Null = unmeasured (unknown).** `confirmed_absent` = genuinely not present in the food. These are different.

In [1]:
import sys
sys.path.insert(0, '../src')

import pandas as pd
from rsu_loader import load_all_rsus, build_food_matrix

In [2]:
rsus = load_all_rsus()
print(f"Loaded {len(rsus)} RSUs")
for rsu in rsus:
    cats = [f.macronutrient_category for f in rsu.staple_foods]
    absent = rsu.absent_categories
    print(f"  {rsu.region_id} {rsu.name}: {cats}" + (f" | absent: {absent}" if absent else ""))

Loaded 12 RSUs
  RSU-01 Boreal Finland: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-02 Boreal Canada: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-03 Siberian Taiga: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-04 Atlantic Western Europe: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-05 Central Europe: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-06 East Asian Temperate: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-07 North American Prairie: ['carb', 'fat', 'protein'] | absent: ['aromatic', 'fermented']
  RSU-08 West African Transition Zone: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-09 Amazon Basin: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-10 Andean Highlands: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-11 South Indian Monsoon: ['carb', 'fat', 'protein', 'aromatic', 'fermented']
  RSU-12 Maritime Southeast Asia: ['carb', 'fat', 'protein', 'aromatic', 'fermented']

## Food matrix — one row per (RSU, food)

In [3]:
df = build_food_matrix(rsus)
print(f"Shape: {df.shape}")
df

Shape: (58, 21)

,region_id,rsu_name,food_name,category,fdc_id,n_confirmed_absent,primary_metabolites.starch_content,primary_metabolites.lipid_content,primary_metabolites.protein_content,organic_acids.lactic_acid,...,organic_acids.malic_acid,primary_metabolites.glucose_concentration,key_flavor_bioactives.tannin_content,organic_acids.acetic_acid,umami_compounds.glutamate,terpenes.pinene,terpenes.linalool,terpenes.limonene,key_flavor_bioactives.capsaicinoids,terpenes.myrcene
0,RSU-01,Boreal Finland,rye bread,carb,2512375,5,88.5810,50.9540,54.1975,-0.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RSU-01,Boreal Finland,Atlantic salmon,fat,2684441,4,NaN,56.5550,60.1595,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RSU-01,Boreal Finland,pike,protein,173680,4,NaN,50.3450,59.6300,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RSU-01,Boreal Finland,cloudberries,aromatic,169802,3,54.3000,50.4000,51.2000,NaN,...,-0.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RSU-01,Boreal Finland,fermented Baltic herring,fermented,175118,4,54.8200,59.0000,57.0950,NaN,...,NaN,53.855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,RSU-02,Boreal Canada,bannock,carb,168058,6,66.9400,50.4900,51.4450,NaN,...,NaN,57.110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,RSU-02,Boreal Canada,moose,fat,174344,4,NaN,50.3700,61.1200,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,RSU-02,Boreal Canada,walleye,protein,2685576,3,54.3935,50.1510,50.8440,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,RSU-02,Boreal Canada,wild blueberries,aromatic,2346411,3,57.2860,50.1530,50.3515,NaN,...,-0.25,NaN,-100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,RSU-02,Boreal Canada,smoked whitefish,fermented,173712,5,NaN,50.4650,61.7000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,RSU-03,Siberian Taiga,buckwheat,carb,2512374,4,87.5090,51.2420,54.4425,NaN,...,NaN,NaN,-3.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,RSU-03,Siberian Taiga,reindeer,fat,171488,4,50.0750,54.4850,59.9050,NaN,...,NaN,50.050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,RSU-03,Siberian Taiga,Arctic char,protein,2685576,3,54.3935,50.1510,50.8440,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,RSU-03,Siberian Taiga,wild lingonberries,aromatic,2685576,3,54.3935,50.1510,50.8440,NaN,...,-0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,RSU-03,Siberian Taiga,fermented reindeer milk,fermented,746766,4,NaN,NaN,NaN,-3.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,RSU-04,Atlantic Western Europe,wheat bread,carb,172686,3,73.7700,52.2650,55.3350,-0.30,...,NaN,52.865,NaN,-0.125,NaN,NaN,NaN,NaN,NaN,NaN
16,RSU-04,Atlantic Western Europe,butter,fat,789828,5,NaN,90.7500,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,RSU-04,Atlantic Western Europe,roast chicken,protein,2646170,4,NaN,50.9670,61.2625,NaN,...,NaN,NaN,NaN,NaN,50.20,NaN,NaN,NaN,NaN,NaN
18,RSU-04,Atlantic Western Europe,thyme,aromatic,170938,4,81.9700,53.7150,54.5550,NaN,...,NaN,50.855,NaN,NaN,NaN,-4.0,-20.0,NaN,NaN,NaN
19,RSU-04,Atlantic Western Europe,Camembert cheese,fermented,328637,4,NaN,NaN,NaN,-0.50,...,NaN,NaN,NaN,NaN,-1.50,NaN,NaN,NaN,NaN,NaN
20,RSU-05,Central Europe,potato,carb,2346404,5,58.6640,50.1875,50.7890,NaN,...,-0.10,NaN,NaN,NaN,50.05,NaN,NaN,NaN,NaN,NaN
21,RSU-05,Central Europe,pork lard,fat,171401,5,NaN,100.0000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,RSU-05,Central Europe,pork,protein,2646168,4,NaN,54.7345,60.5595,NaN,...,NaN,NaN,NaN,NaN,50.17,NaN,NaN,NaN,NaN,NaN
23,RSU-05,Central Europe,caraway,aromatic,170918,5,74.9500,57.2950,59.8850,NaN,...,NaN,50.320,NaN,NaN,NaN,NaN,NaN,-10.0,NaN,NaN
24,RSU-05,Central Europe,sauerkraut,fermented,169279,4,52.1400,50.0700,50.4550,-3.00,...,NaN,50.890,NaN,-0.750,NaN,NaN,NaN,NaN,NaN,NaN
25,RSU-06,East Asian Temperate,rice,carb,2512381,5,90.1565,50.5165,53.5195,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,RSU-06,East Asian Temperate,sesame oil,fat,2262073,5,57.0895,81.2000,59.8525,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,RSU-06,East Asian Temperate,tofu,protein,172475,4,51.3900,54.3600,58.6350,NaN,...,NaN,NaN,NaN,NaN,50.05,NaN,NaN,NaN,NaN,NaN
28,RSU-06,East Asian Temperate,ginger,aromatic,2727584,4,NaN,NaN,50.7340,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,RSU-06,East Asian Temperate,soy sauce,fermented,1104705,4,66.4500,51.6650,75.5500,NaN,...,NaN,NaN,NaN,NaN,-5.00,NaN,NaN,NaN,NaN,NaN
30,RSU-07,North American Prairie,commodity corn,carb,2710826,5,57.3450,50.8130,51.3945,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,RSU-07,North American Prairie,soybean oil,fat,748366,6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,RSU-07,North American Prairie,feedlot beef,protein,2514744,4,NaN,59.7200,58.7655,NaN,...,NaN,NaN,NaN,NaN,50.16,NaN,NaN,NaN,NaN,NaN
33,RSU-08,West African Transition Zone,cassava,carb,2512377,4,93.6565,50.2470,50.4590,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,RSU-08,West African Transition Zone,palm oil,fat,171015,4,NaN,100.0000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,RSU-08,West African Transition Zone,groundnut,protein,2515376,4,63.2490,71.6400,61.6025,NaN,...,NaN,NaN,NaN,NaN,50.35,NaN,NaN,NaN,NaN,NaN
36,RSU-08,West African Transition Zone,Scotch bonnet pepper,aromatic,2258588,3,52.3890,50.0530,50.3575,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-750.00,NaN
37,RSU-08,West African Transition Zone,dawadawa,fermented,2644281,3,79.8975,51.0995,60.7810,NaN,...,NaN,NaN,NaN,NaN,2006.00,NaN,NaN,NaN,NaN,NaN
38,RSU-09,Amazon Basin,cassava,carb,2512377,4,93.6565,50.2470,50.4590,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,RSU-09,Amazon Basin,Brazil nut,fat,2515374,5,68.1445,69.4300,58.7210,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,RSU-09,Amazon Basin,pirarucu,protein,333374,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,RSU-09,Amazon Basin,camu camu,aromatic,167806,4,89.8250,50.2350,51.8450,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,RSU-09,Amazon Basin,chicha,fermented,747432,3,NaN,50.4300,61.6500,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,RSU-10,Andean Highlands,potato,carb,2346404,5,58.6640,50.1875,50.7890,NaN,...,-0.10,NaN,NaN,NaN,50.05,NaN,NaN,NaN,NaN,NaN
44,RSU-10,Andean Highlands,quinoa,fat,2512372,4,84.7625,53.3005,55.9610,NaN,...,NaN,NaN,-2.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,RSU-10,Andean Highlands,guinea pig,protein,172416,4,NaN,53.2250,61.7000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,RSU-10,Andean Highlands,aji amarillo,aromatic,2258588,3,52.3890,50.0530,50.3575,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.50,NaN
47,RSU-10,Andean Highlands,chicha de jora,fermented,168921,3,86.9450,52.5450,54.3750,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,RSU-11,South Indian Monsoon,rice,carb,2512381,5,90.1565,50.5165,53.5195,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,RSU-11,South Indian Monsoon,coconut oil,fat,330458,5,50.4200,99.5500,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,RSU-11,South Indian Monsoon,red lentils,protein,2346408,4,53.3950,50.1070,50.6210,NaN,...,NaN,NaN,NaN,NaN,50.25,NaN,NaN,NaN,NaN,NaN
51,RSU-11,South Indian Monsoon,black pepper,aromatic,2262075,3,67.1775,68.6400,59.0180,NaN,...,NaN,NaN,NaN,NaN,NaN,-5.0,NaN,-2.5,-2.75,-5.0
52,RSU-11,South Indian Monsoon,idli batter,fermented,2644283,4,81.0855,50.9625,61.7845,-2.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,RSU-12,Maritime Southeast Asia,rice,carb,2512381,5,90.1565,50.5165,53.5195,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,RSU-12,Maritime Southeast Asia,coconut milk,fat,170169,5,57.6150,66.7450,51.6650,NaN,...,NaN,53.115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,RSU-12,Maritime Southeast Asia,tempeh,protein,174272,3,53.8200,55.4000,60.1450,2005.00,...,NaN,NaN,NaN,NaN,2005.00,NaN,NaN,NaN,NaN,NaN
56,RSU-12,Maritime Southeast Asia,lemongrass,aromatic,2685576,4,54.3935,50.1510,50.8440,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.0,NaN,-7.5
57,RSU-12,Maritime Southeast Asia,fish sauce,fermented,174531,4,51.8200,50.0050,52.5300,NaN,...,NaN,51.820,NaN,NaN,-5.00,NaN,NaN,NaN,NaN,NaN

## Metabolite field coverage — which fields exist across foods

In [4]:
meta_cols = [c for c in df.columns if '.' in c]
print(f"Metabolite dimensions with at least one measurement: {len(meta_cols)}")

coverage = df[meta_cols].notna().sum().sort_values(ascending=False)
coverage = coverage[coverage > 0]
print(coverage.to_string())

Metabolite dimensions with at least one measurement: 15
primary_metabolites.lipid_content            53
primary_metabolites.protein_content          50
primary_metabolites.starch_content           41
umami_compounds.glutamate                    13
primary_metabolites.glucose_concentration     9
organic_acids.lactic_acid                     7
organic_acids.citric_acid                     6
organic_acids.malic_acid                      5
key_flavor_bioactives.tannin_content          3
terpenes.limonene                             3
key_flavor_bioactives.capsaicinoids           3
organic_acids.acetic_acid                     2
terpenes.pinene                               2
terpenes.myrcene                              2
terpenes.linalool                             1

## Coverage by RSU

In [5]:
rsu_coverage = df.groupby('region_id')[meta_cols].apply(lambda x: x.notna().sum().sum())
rsu_coverage = rsu_coverage.sort_values(ascending=False).rename('n_measured_fields')
print(rsu_coverage.to_string())

region_id
RSU-12    22
RSU-05    21
RSU-11    20
RSU-10    19
RSU-04    18
RSU-01    17
RSU-02    17
RSU-03    17
RSU-08    16
RSU-06    15
RSU-09    12
RSU-07     6

## Coverage by food category

In [6]:
cat_coverage = df.groupby('category')[meta_cols].apply(lambda x: x.notna().sum().sum())
cat_coverage = cat_coverage.sort_values(ascending=False).rename('n_measured_fields')
print(cat_coverage.to_string())

category
aromatic     52
carb         48
fermented    37
protein      36
fat          27

## Confirmed absent vs. unmeasured

These are different. `confirmed_absent` = the compound genuinely does not occur in this food.
Null = we do not have a measurement yet.

In [7]:
absent_rows = []
for rsu in rsus:
    for food in rsu.staple_foods:
        for field in food.confirmed_absent:
            absent_rows.append({'region_id': rsu.region_id, 'food': food.name, 'category': food.macronutrient_category, 'confirmed_absent_field': field})

absent_df = pd.DataFrame(absent_rows)
print(f"Total confirmed-absent entries: {len(absent_df)}")

# Which fields are most consistently absent across the pilot set?
absent_df['confirmed_absent_field'].value_counts()

Total confirmed-absent entries: 237

caffeine_concentration       58
theobromine_concentration    58
capsaicinoids                54
linalool                     38
isothiocyanates               9
lactic_acid                   9
myrcene                       6
tannin_content                5
Name: confirmed_absent_field, dtype: int64

## Data collection priority

Foods with fdc_id = null need FDC search. Run `src/fdc_fetcher.py` to populate.

```bash
export FDC_API_KEY=your_key
cd src && python fdc_fetcher.py
```

In [8]:
no_fdc = df[df['fdc_id'].isna()][['region_id', 'food_name', 'category']].copy()
print(f"Foods without FDC ID: {len(no_fdc)}")
no_fdc

Foods without FDC ID: 0

Empty DataFrame
Columns: [region_id, food_name, category]
Index: []